use crate::skills::types::{DetectConfig, Technology};

pub const GENTLEMAN_PROGRAMMING: Technology = Technology {
    id: "gentleman-programming",
    name: "Gentleman Programming",
    detect: DetectConfig {
        packages: &[],
        package_patterns: &[],
        config_files: &[],
        file_extensions: &[],
        gems: &[],
        config_file_content: &[],
    },
    skills: &[
        "Gentleman-Programming/gentle-ai/branch-pr",
        "Gentleman-Programming/gentle-ai/chained-pr",
        "Gentleman-Programming/gentle-ai/cognitive-doc-design",
        "Gentleman-Programming/gentle-ai/comment-writer",
        "Gentleman-Programming/gentle-ai/gentle-ai-bench",
        "Gentleman-Programming/gentle-ai/go-testing",
        "Gentleman-Programming/gentle-ai/issue-creation",
        "Gentleman-Programming/gentle-ai/judgment-day",
        "Gentleman-Programming/gentle-ai/rdd-defect-workflow",
        "Gentleman-Programming/gentle-ai/sdd-apply",
        "Gentleman-Programming/gentle-ai/sdd-archive",
        "Gentleman-Programming/gentle-ai/sdd-design",
        "Gentleman-Programming/gentle-ai/sdd-explore",
        "Gentleman-Programming/gentle-ai/sdd-init",
        "Gentleman-Programming/gentle-ai/sdd-onboard",
        "Gentleman-Programming/gentle-ai/sdd-propose",
        "Gentleman-Programming/gentle-ai/sdd-spec",
        "Gentleman-Programming/gentle-ai/sdd-tasks",
        "Gentleman-Programming/gentle-ai/sdd-verify",
        "Gentleman-Programming/gentle-ai/skill-creator",
        "Gentleman-Programming/gentle-ai/skill-improver",
        "Gentleman-Programming/gentle-ai/skill-registry",
        "Gentleman-Programming/gentle-ai/systemic-issue-triage",
        "Gentleman-Programming/gentle-ai/work-unit-commits",
    ],
};
