// Domain combo: Forensics & Incident Response — curates security-analysis (forensic), evidence-extraction, security-assessments (forensic), incident-triage (always-suggested domain combo: requires: [] intentionally for visibility)
export const forensicsIrCombo = {
  id: 'forensics-ir',
  name: 'Forensics & Incident Response',
  requires: [] as string[],
  skills: [
    'Gabox301/SkillIndex/analyzing-browser-forensics-with-hindsight',
    'Gabox301/SkillIndex/analyzing-disk-image-with-autopsy',
    'Gabox301/SkillIndex/analyzing-memory-dumps-with-volatility',
    'Gabox301/SkillIndex/analyzing-memory-forensics-with-lime-and-volatility',
    'Gabox301/SkillIndex/analyzing-mft-for-deleted-file-recovery',
    'Gabox301/SkillIndex/analyzing-windows-amcache-artifacts',
    'Gabox301/SkillIndex/analyzing-windows-registry-for-artifacts',
    'Gabox301/SkillIndex/analyzing-linux-system-artifacts',
    'Gabox301/SkillIndex/extracting-browser-history-artifacts',
    'Gabox301/SkillIndex/extracting-credentials-from-memory-dump',
    'Gabox301/SkillIndex/extracting-iocs-from-malware-samples',
    'Gabox301/SkillIndex/extracting-windows-event-logs-artifacts',
    'Gabox301/SkillIndex/performing-disk-forensics-investigation',
    'Gabox301/SkillIndex/performing-memory-forensics-with-volatility3',
    'Gabox301/SkillIndex/performing-memory-forensics-with-volatility3-plugins',
    'Gabox301/SkillIndex/performing-network-forensics-with-wireshark',
    'Gabox301/SkillIndex/performing-cloud-forensics-investigation',
    'Gabox301/SkillIndex/performing-timeline-reconstruction-with-plaso',
    'Gabox301/SkillIndex/performing-log-analysis-for-forensic-investigation',
    'Gabox301/SkillIndex/performing-file-carving-with-foremost',
    'Gabox301/SkillIndex/performing-linux-log-forensics-investigation',
    'Gabox301/SkillIndex/triaging-security-alerts-in-splunk',
    'Gabox301/SkillIndex/triaging-security-incident',
    'Gabox301/SkillIndex/triaging-windows-with-kape',
    'Gabox301/SkillIndex/performing-network-packet-capture-analysis',
  ],
};
