// Domain combo: Red Team / C2 — curates exploitation/threat-hunting/security-engineering + abusing-* (always-suggested domain combo: requires: [] intentionally for visibility)
export const redTeamCombo = {
  id: 'red-team',
  name: 'Red Team & C2 Operations',
  requires: [] as string[],
  skills: [
    'Gabox301/SkillIndex/exploiting-active-directory-certificate-services-esc1',
    'Gabox301/SkillIndex/exploiting-active-directory-with-bloodhound',
    'Gabox301/SkillIndex/exploiting-adcs-with-certipy',
    'Gabox301/SkillIndex/exploiting-constrained-delegation-abuse',
    'Gabox301/SkillIndex/exploiting-kerberoasting-with-impacket',
    'Gabox301/SkillIndex/exploiting-nopac-cve-2021-42278-42287',
    'Gabox301/SkillIndex/exploiting-zerologon-vulnerability-cve-2020-1472',
    'Gabox301/SkillIndex/exploiting-ms17-010-eternalblue-vulnerability',
    'Gabox301/SkillIndex/exploiting-jwt-algorithm-confusion-attack',
    'Gabox301/SkillIndex/exploiting-aws-with-pacu',
    'Gabox301/SkillIndex/hunting-for-cobalt-strike-beacons',
    'Gabox301/SkillIndex/hunting-for-command-and-control-beaconing',
    'Gabox301/SkillIndex/hunting-for-dcsync-attacks',
    'Gabox301/SkillIndex/hunting-for-lateral-movement-via-wmi',
    'Gabox301/SkillIndex/hunting-for-process-injection-techniques',
    'Gabox301/SkillIndex/hunting-for-persistence-mechanisms-in-windows',
    'Gabox301/SkillIndex/hunting-advanced-persistent-threats',
    'Gabox301/SkillIndex/hunting-for-living-off-the-land-binaries',
    'Gabox301/SkillIndex/building-c2-infrastructure-with-sliver-framework',
    'Gabox301/SkillIndex/building-c2-redirector-infrastructure',
    'Gabox301/SkillIndex/building-red-team-c2-infrastructure-with-havoc',
    'Gabox301/SkillIndex/building-adversary-infrastructure-tracking-system',
    'Gabox301/SkillIndex/abusing-dpapi-for-credential-access',
    'Gabox301/SkillIndex/abusing-shadow-credentials-for-privesc',
    'Gabox301/SkillIndex/coercing-authentication-with-coercer-petitpotam',
  ],
};
