use std::env;
use std::fs;
use std::path::Path;
use std::process::Command;

fn main() {
    println!("cargo:rerun-if-changed=skills-map.ts");
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = env::var("OUT_DIR").unwrap();

    let ts_path = Path::new(&manifest_dir).join("skills-map.ts");
    let rs_path = Path::new(&out_dir).join("skills_map.rs");
    let json_out_path = Path::new(&out_dir).join("skills_map.json");

    // Try to generate via Node; fallback to placeholder if Node unavailable
    let json_content = generate_json_via_node(&ts_path).unwrap_or_else(|| {
        // Minimal placeholder — real generation happens when Node is available
        r#"{"skills":[],"combos":[],"frontend_packages":[],"web_frontend_extensions":[]}"#
            .to_string()
    });

    // NOTE: skills_map.json in manifest_dir is a committed source artifact.
    // It must NOT be written by build.rs — Cargo forbids modifying source
    // during `cargo publish --verify` (only OUT_DIR is allowed). To refresh
    // the committed file, run `cargo run -- build` or the Node sync script
    // (`npm run sync:skills` / `scripts/sync-skills.mjs`) explicitly.
    // Here we emit only to OUT_DIR for embedding via include! / SKILLS_MAP_JSON.
    let _ = fs::write(&json_out_path, &json_content);

    // Write Rust file embedding the JSON
    let rs_content = format!(
        r##"// Auto-generated from skills-map.ts — do not edit.
// Generated by build.rs at compile time.

pub const SKILLS_MAP_JSON: &str = r#"{json}"#;

pub fn skills_map_json() -> &'static str {{
    SKILLS_MAP_JSON
}}
"##,
        json = json_content.replace("#", "##")
    );

    let _ = fs::write(&rs_path, rs_content);
}

fn generate_json_via_node(ts_path: &Path) -> Option<String> {
    // Use Node to import the TS file and serialize to JSON
    // We create a temporary ESM script that strips types and extracts maps
    let manifest_dir = ts_path.parent()?.to_str()?;

    // Inline Node script: import skills-map.ts via --experimental-strip-types
    let script = r##"
import { SKILLS_MAP, COMBO_SKILLS_MAP, FRONTEND_PACKAGES, WEB_FRONTEND_EXTENSIONS, FRONTEND_BONUS_SKILLS, AGENT_FOLDER_MAP } from "./skills-map.ts";
import fs from "node:fs";
const out = {
  skills: SKILLS_MAP,
  combos: COMBO_SKILLS_MAP,
  frontend_packages: [...FRONTEND_PACKAGES],
  web_frontend_extensions: [...WEB_FRONTEND_EXTENSIONS],
  frontend_bonus_skills: FRONTEND_BONUS_SKILLS,
  agent_folder_map: AGENT_FOLDER_MAP,
};
// Serialize with RegExp handling: packagePatterns -> string
const json = JSON.stringify(out, (k, v) => {
  if (v instanceof RegExp) return { __regexp: v.source, flags: v.flags };
  if (v instanceof Set) return [...v];
  return v;
}, 2);
process.stdout.write(json);
"##.to_string();

    let output = Command::new("node")
        .arg("--experimental-strip-types")
        .arg("--disable-warning=ExperimentalWarning")
        .arg("-e")
        .arg(script)
        .current_dir(manifest_dir)
        .output()
        .ok()?;

    if !output.status.success() {
        return None;
    }

    let stdout = String::from_utf8(output.stdout).ok()?;
    if stdout.trim().is_empty() {
        return None;
    }
    Some(stdout)
}
