// ── Types ─────────────────────────────────────────────────────
export interface ConfigFileContentBlock {
  files?: string[];
  patterns: string[];
  scanGradleLayout?: boolean;
  scanDotNetLayout?: boolean;
}
export interface DetectConfig {
  packages?: string[];
  packagePatterns?: RegExp[];
  configFiles?: string[];
  fileExtensions?: string[];
  gems?: string[];
  configFileContent?: ConfigFileContentBlock | ConfigFileContentBlock[];
}
export interface Technology {
  id: string;
  name: string;
  detect: DetectConfig;
  skills: string[];
}
export interface ComboSkill {
  id: string;
  name: string;
  requires: string[];
  skills: string[];
}

import { cloudSecurityCombo } from './skills/combos/cloud-security.ts';
import { forensicsIrCombo } from './skills/combos/forensics-ir.ts';
import { redTeamCombo } from './skills/combos/red-team.ts';
import { securityOperationsCombo } from './skills/combos/security-operations.ts';
import { activeDirectoryTech } from './skills/security/active-directory.ts';
import { threatDetectionTech } from './skills/security/threat-detection.ts';
import { securityImplementationTech } from './skills/security/security-implementation.ts';
import { securityAnalysisTech } from './skills/security/security-analysis.ts';
import { threatHuntingTech } from './skills/security/threat-hunting.ts';
import { awsTech } from './skills/techs/aws.ts';

// ── Skills Map ────────────────────────────────────────────────
export const SKILLS_MAP: Technology[] = [
  {
    id: 'react',
    name: 'React',
    detect: {
      packages: ['react', 'react-dom'],
    },
    skills: ['vercel-labs/agent-skills/react-best-practices', 'vercel-labs/agent-skills/composition-patterns'],
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    detect: {
      packages: ['next'],
      configFiles: ['next.config.js', 'next.config.mjs', 'next.config.ts'],
    },
    skills: [
      'vercel-labs/next-skills/next-best-practices',
      'vercel-labs/next-skills/next-cache-components',
      'vercel-labs/next-skills/next-upgrade',
    ],
  },
  {
    id: 'vue',
    name: 'Vue',
    detect: {
      packages: ['vue'],
    },
    skills: ['hyf0/vue-skills/vue-debug-guides', 'antfu/skills/vue', 'antfu/skills/vue-best-practices'],
  },
  {
    id: 'nuxt',
    name: 'Nuxt',
    detect: {
      packages: ['nuxt'],
      configFiles: ['nuxt.config.js', 'nuxt.config.ts'],
    },
    skills: ['antfu/skills/nuxt'],
  },
  {
    id: 'pinia',
    name: 'Pinia',
    detect: {
      packages: ['pinia'],
    },
    skills: ['vuejs-ai/skills/vue-pinia-best-practices'],
  },
  {
    id: 'svelte',
    name: 'Svelte',
    detect: {
      packages: ['svelte', '@sveltejs/kit'],
      configFiles: ['svelte.config.js'],
    },
    skills: ['ejirocodes/agent-skills/svelte5-best-practices', 'sveltejs/ai-tools/svelte-code-writer'],
  },
  {
    id: 'angular',
    name: 'Angular',
    detect: {
      packages: ['@angular/core'],
      configFiles: ['angular.json'],
    },
    skills: [
      'angular/skills/angular-developer',
      'angular/angular/reference-core',
      'angular/angular/reference-signal-forms',
      'angular/angular/reference-compiler-cli',
      'angular/angular/adev-writing-guide',
      'angular/angular/pr_review',
    ],
  },
  {
    id: 'astro',
    name: 'Astro',
    detect: {
      packages: ['astro'],
      configFiles: ['astro.config.mjs', 'astro.config.js', 'astro.config.ts'],
    },
    skills: ['astrolicious/agent-skills/astro'],
  },
  {
    id: 'tailwind',
    name: 'Tailwind CSS',
    detect: {
      packages: ['tailwindcss', '@tailwindcss/vite'],
      configFiles: ['tailwind.config.js', 'tailwind.config.ts', 'tailwind.config.cjs'],
    },
    skills: ['giuseppe-trisciuoglio/developer-kit/tailwind-css-patterns'],
  },
  {
    id: 'shadcn',
    name: 'shadcn/ui',
    detect: {
      configFiles: ['components.json'],
    },
    skills: ['shadcn/ui/shadcn'],
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    detect: {
      packages: ['typescript'],
      configFiles: ['tsconfig.json'],
    },
    skills: ['wshobson/agents/typescript-advanced-types'],
  },
  {
    id: 'react-hook-form',
    name: 'React Hook Form',
    detect: {
      packages: ['react-hook-form'],
    },
    skills: ['pproenca/dot-skills/react-hook-form'],
  },
  {
    id: 'zod',
    name: 'Zod',
    detect: {
      packages: ['zod'],
    },
    skills: ['pproenca/dot-skills/zod'],
  },
  {
    id: 'supabase',
    name: 'Supabase',
    detect: {
      packages: ['@supabase/supabase-js', '@supabase/ssr'],
    },
    skills: ['supabase/agent-skills/supabase-postgres-best-practices'],
  },
  {
    id: 'neon',
    name: 'Neon Postgres',
    detect: {
      packages: ['@neondatabase/serverless'],
    },
    skills: ['neondatabase/agent-skills/neon-postgres'],
  },
  {
    id: 'instantdb',
    name: 'InstantDB',
    detect: {
      packages: [
        '@instantdb/core',
        '@instantdb/react',
        '@instantdb/react-native',
        '@instantdb/react-native-mmkv',
        '@instantdb/admin',
      ],
      configFiles: ['instant.schema.ts', 'instant.perms.ts'],
    },
    skills: ['instantdb/skills/instantdb'],
  },
  {
    id: 'playwright',
    name: 'Playwright',
    detect: {
      packages: ['@playwright/test', 'playwright'],
      configFiles: ['playwright.config.ts', 'playwright.config.js'],
    },
    skills: ['currents-dev/playwright-best-practices-skill/playwright-best-practices'],
  },
  {
    id: 'expo',
    name: 'Expo',
    detect: {
      packages: ['expo'],
    },
    skills: [
      'expo/skills/building-native-ui',
      'expo/skills/native-data-fetching',
      'expo/skills/upgrading-expo',
      'expo/skills/expo-tailwind-setup',
      'expo/skills/expo-dev-client',
      'expo/skills/expo-deployment',
      'expo/skills/expo-cicd-workflows',
      'expo/skills/expo-api-routes',
      'expo/skills/use-dom',
    ],
  },
  {
    id: 'react-native',
    name: 'React Native',
    detect: {
      packages: ['react-native'],
    },
    skills: ['sleekdotdesign/agent-skills/design-mobile-apps'],
  },
  {
    id: 'dart',
    name: 'Dart',
    detect: {
      configFiles: ['pubspec.yaml'],
    },
    skills: ['kevmoo/dash_skills/dart-best-practices'],
  },
  {
    id: 'flutter',
    name: 'Flutter',
    detect: {
      configFileContent: {
        patterns: ['flutter:'],
        files: ['pubspec.yaml'],
      },
    },
    skills: [
      'jeffallan/claude-skills/flutter-expert',
      'madteacher/mad-agents-skills/flutter-animations',
      'madteacher/mad-agents-skills/flutter-testing',
    ],
  },
  {
    id: 'kotlin-multiplatform',
    name: 'Kotlin Multiplatform',
    detect: {
      configFileContent: {
        scanGradleLayout: true,
        patterns: [
          'kotlin("multiplatform")',
          'org.jetbrains.kotlin.multiplatform',
          'id("org.jetbrains.kotlin.multiplatform")',
          'kotlin-multiplatform',
        ],
      },
    },
    skills: [
      'Kotlin/kotlin-agent-skills/kotlin-tooling-cocoapods-spm-migration',
      'Kotlin/kotlin-agent-skills/kotlin-tooling-agp9-migration',
    ],
  },
  {
    id: 'android',
    name: 'Android',
    detect: {
      configFileContent: {
        scanGradleLayout: true,
        patterns: [
          'com.android.application',
          'com.android.library',
          'id("com.android.application")',
          'id("com.android.library")',
          'com.android.kotlin.multiplatform.library',
        ],
      },
    },
    skills: [
      'krutikJain/android-agent-skills/android-kotlin-core',
      'krutikJain/android-agent-skills/android-compose-foundations',
      'krutikJain/android-agent-skills/android-architecture-clean',
      'krutikJain/android-agent-skills/android-di-hilt',
      'krutikJain/android-agent-skills/android-gradle-build-logic',
      'krutikJain/android-agent-skills/android-coroutines-flow',
      'krutikJain/android-agent-skills/android-networking-retrofit-okhttp',
      'krutikJain/android-agent-skills/android-testing-unit',
    ],
  },
  {
    id: 'remotion',
    name: 'Remotion',
    detect: {
      packages: ['remotion', '@remotion/cli'],
    },
    skills: ['remotion-dev/skills/remotion'],
  },
  {
    id: 'react-router',
    name: 'React Router',
    detect: {
      packages: ['react-router', '@react-router/node', '@react-router/dev', '@react-router/serve'],
    },
    skills: ['clerk/skills/clerk-react-router-patterns'],
  },
  {
    id: 'tanstack-start',
    name: 'TanStack Start',
    detect: {
      packages: ['@tanstack/react-start', '@tanstack/start'],
    },
    skills: ['tanstack-skills/tanstack-skills/tanstack-start'],
  },
  {
    id: 'chrome-extension',
    name: 'Chrome Extension',
    detect: {
      configFileContent: {
        files: ['manifest.json'],
        patterns: ['manifest_version'],
      },
    },
    skills: ['mindrally/skills/chrome-extension-development'],
  },
  {
    id: 'clerk',
    name: 'Clerk',
    detect: {
      packages: [
        '@clerk/nextjs',
        '@clerk/remix',
        '@clerk/astro',
        '@clerk/express',
        '@clerk/fastify',
        '@clerk/nuxt',
        '@clerk/vue',
        '@clerk/react',
        '@clerk/expo',
        '@clerk/tanstack-react-start',
        '@clerk/react-router',
        '@clerk/chrome-extension',
        '@clerk/backend',
      ],
      packagePatterns: [/^@clerk\//],
      configFileContent: [
        {
          files: ['Package.swift'],
          patterns: ['clerk/clerk-ios', 'ClerkSDK'],
        },
        {
          scanGradleLayout: true,
          patterns: ['com.clerk'],
        },
      ],
    },
    skills: [
      'clerk/skills/clerk',
      'clerk/skills/clerk-setup',
      'clerk/skills/clerk-custom-ui',
      'clerk/skills/clerk-backend-api',
      'clerk/skills/clerk-orgs',
      'clerk/skills/clerk-webhooks',
      'clerk/skills/clerk-testing',
    ],
  },
  {
    id: 'better-auth',
    name: 'Better Auth',
    detect: {
      packages: ['better-auth'],
    },
    skills: [
      'better-auth/skills/best-practices',
      'better-auth/skills/emailAndPassword',
      'better-auth/skills/organization',
      'better-auth/skills/twoFactor',
    ],
  },
  {
    id: 'turborepo',
    name: 'Turborepo',
    detect: {
      packages: ['turbo'],
      configFiles: ['turbo.json'],
    },
    skills: ['vercel/turborepo/turborepo'],
  },
  {
    id: 'vite',
    name: 'Vite',
    detect: {
      packages: ['vite'],
      configFiles: ['vite.config.js', 'vite.config.ts', 'vite.config.mjs'],
    },
    skills: ['antfu/skills/vite'],
  },
  {
    id: 'azure',
    name: 'Azure',
    detect: {
      packagePatterns: [/^@azure\//],
    },
    skills: [
      'microsoft/github-copilot-for-azure/azure-deploy',
      'microsoft/github-copilot-for-azure/azure-ai',
      'microsoft/github-copilot-for-azure/azure-cost',
      'microsoft/github-copilot-for-azure/azure-diagnostics',
    ],
  },
  {
    id: 'vercel-ai',
    name: 'Vercel AI SDK',
    detect: {
      packages: ['ai', '@ai-sdk/openai', '@ai-sdk/anthropic', '@ai-sdk/google'],
    },
    skills: ['vercel/ai/use-ai-sdk'],
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    detect: {
      packages: ['elevenlabs'],
    },
    skills: ['inferen-sh/skills/elevenlabs-tts', 'inferen-sh/skills/elevenlabs-music'],
  },
  {
    id: 'vercel-deploy',
    name: 'Vercel',
    detect: {
      configFiles: ['vercel.json', '.vercel'],
      packages: ['vercel', '@astrojs/vercel'],
    },
    skills: ['vercel-labs/agent-skills/deploy-to-vercel'],
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    detect: {
      packages: ['wrangler', '@cloudflare/workers-types', '@astrojs/cloudflare'],
      configFiles: ['wrangler.toml', 'wrangler.json', 'wrangler.jsonc'],
    },
    skills: [
      'cloudflare/skills/cloudflare',
      'cloudflare/skills/wrangler',
      'cloudflare/skills/workers-best-practices',
      'cloudflare/skills/web-perf',
      'openai/skills/cloudflare-deploy',
    ],
  },
  {
    id: 'cloudflare-durable-objects',
    name: 'Durable Objects',
    detect: {
      configFileContent: {
        files: ['wrangler.json', 'wrangler.jsonc', 'wrangler.toml'],
        patterns: ['durable_objects'],
      },
    },
    skills: ['cloudflare/skills/durable-objects'],
  },
  {
    id: 'cloudflare-agents',
    name: 'Cloudflare Agents',
    detect: {
      packages: ['agents'],
    },
    skills: ['cloudflare/skills/agents-sdk', 'cloudflare/skills/sandbox-sdk'],
  },
  {
    id: 'cloudflare-ai',
    name: 'Cloudflare AI',
    detect: {
      packages: ['@cloudflare/ai'],
      configFileContent: {
        files: ['wrangler.json', 'wrangler.jsonc'],
        patterns: ['"ai"'],
      },
    },
    skills: ['cloudflare/skills/agents-sdk'],
  },
  {
    id: 'terraform',
    name: 'Terraform',
    detect: {
      configFiles: ['.terraform.lock.hcl', 'terraform.tfvars', 'main.tf', 'variables.tf', 'outputs.tf'],
    },
    skills: [
      'hashicorp/agent-skills/terraform-style-guide',
      'hashicorp/agent-skills/refactor-module',
      'hashicorp/agent-skills/terraform-stacks',
      'wshobson/agents/terraform-module-library',
    ],
  },
    awsTech,
    activeDirectoryTech,
    threatDetectionTech,
    securityImplementationTech,
    securityAnalysisTech,
    threatHuntingTech,
  {
    id: 'swiftui',
    name: 'SwiftUI',
    detect: {
      configFiles: ['Package.swift', 'Podfile'],
    },
    skills: [
      'avdlee/swiftui-agent-skill/swiftui-expert-skill',
      'avdlee/swift-concurrency-agent-skill/swift-concurrency',
      'avdlee/xcode-build-optimization-agent-skill/xcode-build-orchestrator',
      'avdlee/swift-testing-agent-skill/swift-testing-expert',
      'avdlee/core-data-agent-skill/core-data-expert',
    ],
  },
  {
    id: 'oxlint',
    name: 'oxlint',
    detect: {
      packages: ['oxlint'],
      configFiles: ['.oxlintrc.json', 'oxlint.config.ts'],
    },
    skills: ['delexw/claude-code-misc/oxlint'],
  },
  {
    id: 'gsap',
    name: 'GSAP',
    detect: {
      packages: ['gsap'],
    },
    skills: [
      'greensock/gsap-skills/gsap-core',
      'greensock/gsap-skills/gsap-scrolltrigger',
      'greensock/gsap-skills/gsap-performance',
      'greensock/gsap-skills/gsap-plugins',
      'greensock/gsap-skills/gsap-timeline',
      'greensock/gsap-skills/gsap-utils',
      'greensock/gsap-skills/gsap-frameworks',
    ],
  },
  {
    id: 'threejs',
    name: 'Three.js',
    detect: {
      packages: ['three'],
    },
    skills: [
      'cloudai-x/threejs-skills/threejs-animation',
      'cloudai-x/threejs-skills/threejs-fundamentals',
      'cloudai-x/threejs-skills/threejs-shaders',
      'cloudai-x/threejs-skills/threejs-geometry',
      'cloudai-x/threejs-skills/threejs-interaction',
      'cloudai-x/threejs-skills/threejs-materials',
      'cloudai-x/threejs-skills/threejs-postprocessing',
      'cloudai-x/threejs-skills/threejs-lighting',
      'cloudai-x/threejs-skills/threejs-textures',
      'cloudai-x/threejs-skills/threejs-loaders',
    ],
  },
  {
    id: '@react-three/fiber',
    name: 'React Three Fiber',
    detect: {
      packages: ['@react-three/fiber'],
    },
    skills: ['vercel-labs/json-render/react-three-fiber'],
  },
  {
    id: 'bun',
    name: 'Bun',
    detect: {
      configFiles: ['bun.lockb', 'bun.lock', 'bunfig.toml'],
    },
    skills: ['Gabox301/SkillIndex/bun'],
  },
  {
    id: 'elysia',
    name: 'Elysia',
    detect: {
      packages: ['elysia'],
    },
    skills: ['elysiajs/skills/elysiajs'],
  },
  {
    id: 'node',
    name: 'Node.js',
    detect: {
      configFiles: ['package-lock.json', 'yarn.lock', 'pnpm-lock.yaml', '.nvmrc', '.node-version'],
    },
    skills: ['wshobson/agents/nodejs-backend-patterns', 'sickn33/antigravity-awesome-skills/nodejs-best-practices'],
  },
  {
    id: 'bash',
    name: 'Bash',
    detect: {
      fileExtensions: ['.sh', '.bash'],
    },
    skills: ['wshobson/agents/bash-defensive-patterns'],
  },
  {
    id: 'express',
    name: 'Express',
    detect: {
      packages: ['express'],
    },
    skills: ['aj-geddes/useful-ai-prompts/nodejs-express-server'],
  },
  {
    id: 'go',
    name: 'Go',
    detect: {
      configFiles: ['go.mod', 'go.work'],
    },
    skills: ['affaan-m/everything-claude-code/golang-patterns', 'affaan-m/everything-claude-code/golang-testing'],
  },
  {
    id: 'deno',
    name: 'Deno',
    detect: {
      configFiles: ['deno.json', 'deno.jsonc', 'deno.lock'],
    },
    skills: [
      'denoland/skills/deno-expert',
      'denoland/skills/deno-guidance',
      'denoland/skills/deno-frontend',
      'denoland/skills/deno-deploy',
      'denoland/skills/deno-sandbox',
      'mindrally/skills/deno-typescript',
    ],
  },
  {
    id: 'wordpress',
    name: 'WordPress',
    detect: {
      configFiles: ['wp-config.php', 'wp-login.php'],
      packagePatterns: [/^@wordpress\//],
      configFileContent: {
        files: ['composer.json', 'style.css'],
        patterns: ['johnpbloch/wordpress', 'wpackagist', 'Theme Name:'],
      },
    },
    skills: [
      'wordpress/agent-skills/wp-plugin-development',
      'wordpress/agent-skills/wp-rest-api',
      'wordpress/agent-skills/wp-block-themes',
      'wordpress/agent-skills/wp-block-development',
      'wordpress/agent-skills/wp-performance',
      'wordpress/agent-skills/wordpress-router',
      'wordpress/agent-skills/wp-project-triage',
      'wordpress/agent-skills/wp-wpcli-and-ops',
    ],
  },
  {
    id: 'java',
    name: 'Java',
    detect: {
      configFiles: ['pom.xml'],
      configFileContent: {
        scanGradleLayout: true,
        patterns: [
          'sourceCompatibility',
          'targetCompatibility',
          'JavaVersion',
          'id("java")',
          "id 'java'",
          'id("java-library")',
          "id 'java-library'",
        ],
      },
    },
    skills: ['github/awesome-copilot/java-docs', 'affaan-m/everything-claude-code/java-coding-standards'],
  },
  {
    id: 'springboot',
    name: 'Spring Boot',
    detect: {
      configFiles: [
        'src/main/resources/application.properties',
        'src/main/resources/application.yml',
        'src/main/resources/application.yaml',
      ],
      configFileContent: {
        files: ['pom.xml'],
        patterns: ['spring-boot-starter', 'org.springframework.boot'],
      },
    },
    skills: ['github/awesome-copilot/java-springboot'],
  },
  {
    id: 'prisma',
    name: 'Prisma',
    detect: {
      packages: ['prisma', '@prisma/client'],
    },
    skills: [
      'prisma/skills/prisma-database-setup',
      'prisma/skills/prisma-client-api',
      'prisma/skills/prisma-cli',
      'prisma/skills/prisma-postgres',
    ],
  },
  {
    id: 'stripe',
    name: 'Stripe',
    detect: {
      packages: ['stripe', '@stripe/stripe-js', '@stripe/react-stripe-js'],
    },
    skills: ['stripe/ai/stripe-best-practices', 'stripe/ai/upgrade-stripe'],
  },
  {
    id: 'hono',
    name: 'Hono',
    detect: {
      packages: ['hono'],
    },
    skills: ['yusukebe/hono-skill/hono'],
  },
  {
    id: 'vitest',
    name: 'Vitest',
    detect: {
      packages: ['vitest'],
      configFiles: ['vitest.config.ts', 'vitest.config.js', 'vitest.config.mts'],
    },
    skills: ['antfu/skills/vitest'],
  },
  {
    id: 'drizzle',
    name: 'Drizzle ORM',
    detect: {
      packages: ['drizzle-orm', 'drizzle-kit'],
    },
    skills: ['bobmatnyc/claude-mpm-skills/drizzle'],
  },
  {
    id: 'nestjs',
    name: 'NestJS',
    detect: {
      packages: ['@nestjs/core'],
    },
    skills: ['kadajett/agent-nestjs-skills/nestjs-best-practices'],
  },
  {
    id: 'tauri',
    name: 'Tauri',
    detect: {
      packages: ['@tauri-apps/api', '@tauri-apps/cli'],
      configFiles: ['src-tauri/tauri.conf.json'],
    },
    skills: ['nodnarbnitram/claude-code-extensions/tauri-v2'],
  },
  {
    id: 'electron',
    name: 'Electron',
    detect: {
      packages: ['electron'],
      configFiles: [
        'electron-builder.yml',
        'electron-builder.json',
        'electron-builder.js',
        'forge.config.js',
        'forge.config.cjs',
        'forge.config.mjs',
        'forge.config.ts',
        'electron-vite.config.ts',
        'electron-vite.config.js',
        'electron-vite.config.mjs',
        'electron-vite.config.cjs',
      ],
    },
    skills: [
      'full-stack-skills/electron-skills/electron',
      'full-stack-skills/electron-skills/electron-egg',
      'full-stack-skills/electron-skills/upgradeLink',
    ],
  },
  {
    id: 'dotnet',
    name: '.NET',
    detect: {
      configFiles: ['global.json', 'NuGet.Config', 'Directory.Build.props', 'Directory.Packages.props'],
      configFileContent: {
        scanDotNetLayout: true,
        patterns: ['<Project Sdk="Microsoft.NET.Sdk'],
      },
    },
    skills: [
      'github/awesome-copilot/dotnet-best-practices',
      'github/awesome-copilot/dotnet-design-pattern-review',
      'github/awesome-copilot/dotnet-upgrade',
    ],
  },
  {
    id: 'csharp',
    name: 'C#',
    detect: {
      configFileContent: {
        scanDotNetLayout: true,
        patterns: ['<Project', 'Microsoft.NET.Sdk'],
      },
    },
    skills: [
      'github/awesome-copilot/csharp-xunit',
      'github/awesome-copilot/csharp-async',
      'github/awesome-copilot/csharp-docs',
      'github/awesome-copilot/csharp-nunit',
      'github/awesome-copilot/csharp-mstest',
      'github/awesome-copilot/csharp-tunit',
    ],
  },
  {
    id: 'aspnetcore',
    name: 'ASP.NET Core',
    detect: {
      configFiles: ['appsettings.json', 'appsettings.Development.json'],
      configFileContent: {
        scanDotNetLayout: true,
        patterns: ['Microsoft.NET.Sdk.Web'],
      },
    },
    skills: ['github/awesome-copilot/containerize-aspnetcore', 'openai/skills/aspnet-core'],
  },
  {
    id: 'aspnet-blazor',
    name: 'Blazor',
    detect: {
      configFileContent: {
        scanDotNetLayout: true,
        patterns: ['Microsoft.NET.Sdk.BlazorWebAssembly', 'Microsoft.AspNetCore.Components'],
      },
    },
    skills: ['github/awesome-copilot/fluentui-blazor'],
  },
  {
    id: 'aspnet-minimal-api',
    name: 'ASP.NET Minimal API',
    detect: {
      configFiles: ['appsettings.json'],
      configFileContent: {
        scanDotNetLayout: true,
        patterns: ['Microsoft.AspNetCore.OpenApi', 'Swashbuckle.AspNetCore'],
      },
    },
    skills: ['github/awesome-copilot/aspnet-minimal-api-openapi', 'dotnet/skills/minimal-api-file-upload'],
  },
  {
    id: 'rust',
    name: 'Rust',
    detect: {
      configFiles: ['Cargo.toml'],
    },
    skills: ['apollographql/skills/rust-best-practices'],
  },
  {
    id: 'ruby',
    name: 'Ruby',
    detect: {
      configFiles: ['Gemfile', 'Gemfile.lock', '.ruby-version', '.ruby-gemset'],
    },
    skills: ['lucianghinda/superpowers-ruby/ruby'],
  },
  {
    id: 'rails',
    name: 'Ruby on Rails',
    detect: {
      gems: ['rails'],
      configFiles: ['config/routes.rb', 'config/application.rb', 'bin/rails'],
    },
    skills: [
      'sergiodxa/agent-skills/ruby-on-rails-best-practices',
      'lucianghinda/superpowers-ruby/rails-guides',
      'igmarin/rails-agent-skills/rails-stack-conventions',
      'igmarin/rails-agent-skills/rails-code-review',
      'igmarin/rails-agent-skills/rails-migration-safety',
      'igmarin/rails-agent-skills/rails-security-review',
      'ombulabs/claude-code_rails-upgrade-skill/rails-upgrade',
    ],
  },
  {
    id: 'redis-ruby',
    name: 'Redis (Ruby)',
    detect: {
      gems: ['redis', 'sidekiq', 'resque', 'redis-rails'],
    },
    skills: ['redis/agent-skills/redis-development'],
  },
  {
    id: 'sorbet',
    name: 'Sorbet',
    detect: {
      gems: ['sorbet', 'sorbet-runtime'],
      configFiles: ['sorbet/config'],
    },
    skills: [
      'DmitryPogrebnoy/ruby-agent-skills/generating-sorbet',
      'DmitryPogrebnoy/ruby-agent-skills/generating-sorbet-inline',
    ],
  },
  {
    id: 'sidekiq',
    name: 'Sidekiq',
    detect: {
      gems: ['sidekiq'],
    },
    skills: ['igmarin/rails-agent-skills/rails-background-jobs'],
  },
  {
    id: 'rspec',
    name: 'RSpec',
    detect: {
      gems: ['rspec', 'rspec-rails'],
      configFiles: ['.rspec'],
    },
    skills: [
      'igmarin/rails-agent-skills/rspec-best-practices',
      'igmarin/rails-agent-skills/rspec-service-testing',
      'lucianghinda/superpowers-ruby/test-driven-development',
    ],
  },
  {
    id: 'rubocop',
    name: 'RuboCop',
    detect: {
      gems: ['rubocop', 'rubocop-rails'],
      configFiles: ['.rubocop.yml'],
    },
    skills: [
      'TheBushidoCollective/han/rubocop-configuration',
      'TheBushidoCollective/han/rubocop-cops',
      'TheBushidoCollective/han/rubocop-integration',
    ],
  },
  {
    id: 'php',
    name: 'PHP',
    detect: {
      configFiles: ['composer.json', 'composer.lock'],
    },
    skills: ['jeffallan/claude-skills/php-pro'],
  },
  {
    id: 'laravel',
    name: 'Laravel',
    detect: {
      configFiles: ['artisan', 'bootstrap/app.php'],
      configFileContent: {
        files: ['composer.json'],
        patterns: ['"laravel/framework"', '"illuminate/'],
      },
    },
    skills: ['jeffallan/claude-skills/laravel-specialist', 'affaan-m/everything-claude-code/laravel-patterns'],
  },
  {
    id: 'python',
    name: 'Python',
    detect: {
      configFiles: ['pyproject.toml', 'requirements.txt', 'setup.py', 'Pipfile'],
    },
    skills: ['inferen-sh/skills/python-executor', 'wshobson/agents/python-testing-patterns'],
  },
  {
    id: 'fastapi',
    name: 'FastAPI',
    detect: {
      configFileContent: {
        files: ['pyproject.toml', 'requirements.txt', 'setup.py', 'Pipfile'],
        patterns: ['fastapi', 'FastAPI'],
      },
    },
    skills: ['wshobson/agents/fastapi-templates', 'mindrally/skills/fastapi-python'],
  },
  {
    id: 'fastmcp',
    name: 'FastMCP',
    detect: {
      configFileContent: {
        files: ['pyproject.toml', 'requirements.txt', 'setup.py', 'Pipfile'],
        patterns: ['fastmcp', 'FastMCP'],
      },
    },
    skills: ['sharanharsoor/skills/fastmcp'],
  },
  {
    id: 'django',
    name: 'Django',
    detect: {
      configFileContent: {
        files: ['pyproject.toml', 'requirements.txt', 'setup.py', 'Pipfile'],
        patterns: ['django', 'Django'],
      },
    },
    skills: [
      'vintasoftware/django-ai-plugins/django-expert',
      'affaan-m/everything-claude-code/django-patterns',
      'affaan-m/everything-claude-code/django-security',
    ],
  },
  {
    id: 'flask',
    name: 'Flask',
    detect: {
      configFileContent: {
        files: ['pyproject.toml', 'requirements.txt', 'setup.py', 'setup.cfg', 'Pipfile'],
        patterns: ['flask', 'Flask'],
      },
    },
    skills: ['aj-geddes/useful-ai-prompts/flask-api-development'],
  },
  {
    id: 'pydantic',
    name: 'Pydantic',
    detect: {
      configFileContent: {
        files: ['pyproject.toml', 'requirements.txt', 'setup.py', 'Pipfile'],
        patterns: ['pydantic', 'Pydantic'],
      },
    },
    skills: ['bobmatnyc/claude-mpm-skills/pydantic'],
  },
  {
    id: 'sqlalchemy',
    name: 'SQLAlchemy',
    detect: {
      configFileContent: {
        files: ['pyproject.toml', 'requirements.txt', 'setup.py', 'Pipfile'],
        patterns: ['sqlalchemy', 'SQLAlchemy'],
      },
    },
    skills: [
      'bobmatnyc/claude-mpm-skills/sqlalchemy',
      'wispbit-ai/skills/sqlalchemy-alembic-expert-best-practices-code-review',
    ],
  },
  {
    id: 'pytest',
    name: 'Pytest',
    detect: {
      configFileContent: {
        files: ['pyproject.toml', 'requirements.txt', 'setup.py', 'Pipfile'],
        patterns: ['pytest', 'Pytest'],
      },
    },
    skills: ['wshobson/agents/python-testing-patterns'],
  },
  {
    id: 'pandas',
    name: 'Pandas',
    detect: {
      configFileContent: {
        files: ['pyproject.toml', 'requirements.txt', 'setup.py', 'Pipfile'],
        patterns: ['pandas', 'Pandas'],
      },
    },
    skills: ['jeffallan/claude-skills/pandas-pro', 'pluginagentmarketplace/custom-plugin-python/pandas-data-analysis'],
  },
  {
    id: 'numpy',
    name: 'NumPy',
    detect: {
      configFileContent: {
        files: ['pyproject.toml', 'requirements.txt', 'setup.py', 'Pipfile'],
        patterns: ['numpy', 'NumPy', 'numpy'],
      },
    },
    skills: [
      'pluginagentmarketplace/custom-plugin-python/machine-learning',
      'pluginagentmarketplace/custom-plugin-python/pandas-data-analysis',
    ],
  },
  {
    id: 'scikit-learn',
    name: 'Scikit-Learn',
    detect: {
      configFileContent: {
        files: ['pyproject.toml', 'requirements.txt', 'setup.py', 'Pipfile'],
        patterns: ['scikit-learn', 'scikit_learn', 'sklearn'],
      },
    },
    skills: ['davila7/claude-code-templates/scikit-learn', 'davila7/claude-code-templates/senior-data-scientist'],
  },
  {
    id: 'celery',
    name: 'Celery',
    detect: {
      configFileContent: {
        files: ['pyproject.toml', 'requirements.txt', 'setup.py', 'Pipfile'],
        patterns: ['celery', 'Celery'],
      },
    },
    skills: ['wshobson/agents/python-background-jobs'],
  },
  {
    id: 'requests',
    name: 'Requests',
    detect: {
      configFileContent: {
        files: ['pyproject.toml', 'requirements.txt', 'setup.py', 'Pipfile'],
        patterns: ['requests', 'Requests'],
      },
    },
    skills: ['affaan-m/everything-claude-code/python-patterns'],
  },
  {
    id: 'orphan-performing',
    name: 'Performing Skills',
    detect: {},
    skills: [
      'Gabox301/SkillIndex/performing-access-recertification-with-saviynt',
      'Gabox301/SkillIndex/performing-access-review-and-certification',
      'Gabox301/SkillIndex/performing-adversary-in-the-middle-phishing-detection',
      'Gabox301/SkillIndex/performing-agentless-vulnerability-scanning',
      'Gabox301/SkillIndex/performing-ai-driven-osint-correlation',
      'Gabox301/SkillIndex/performing-alert-triage-with-elastic-siem',
      'Gabox301/SkillIndex/performing-android-app-static-analysis-with-mobsf',
      'Gabox301/SkillIndex/performing-api-fuzzing-with-restler',
      'Gabox301/SkillIndex/performing-api-inventory-and-discovery',
      'Gabox301/SkillIndex/performing-api-rate-limiting-bypass',
      'Gabox301/SkillIndex/performing-api-security-testing-with-postman',
      'Gabox301/SkillIndex/performing-arp-spoofing-attack-simulation',
      'Gabox301/SkillIndex/performing-asset-criticality-scoring-for-vulns',
      'Gabox301/SkillIndex/performing-authenticated-scan-with-openvas',
      'Gabox301/SkillIndex/performing-authenticated-vulnerability-scan',
      'Gabox301/SkillIndex/performing-automated-malware-analysis-with-cape',
      'Gabox301/SkillIndex/performing-bandwidth-throttling-attack-simulation',
      'Gabox301/SkillIndex/performing-binary-exploitation-analysis',
      'Gabox301/SkillIndex/performing-blind-ssrf-exploitation',
      'Gabox301/SkillIndex/performing-bluetooth-security-assessment',
      'Gabox301/SkillIndex/performing-brand-monitoring-for-impersonation',
      'Gabox301/SkillIndex/performing-clickjacking-attack-test',
      'Gabox301/SkillIndex/performing-cloud-asset-inventory-with-cartography',
      'Gabox301/SkillIndex/performing-cloud-forensics-investigation',
      'Gabox301/SkillIndex/performing-cloud-incident-containment-procedures',
      'Gabox301/SkillIndex/performing-cloud-log-forensics-with-athena',
      'Gabox301/SkillIndex/performing-cloud-native-forensics-with-falco',
      'Gabox301/SkillIndex/performing-cloud-penetration-testing-with-pacu',
      'Gabox301/SkillIndex/performing-cloud-storage-forensic-acquisition',
      'Gabox301/SkillIndex/performing-container-escape-detection',
      'Gabox301/SkillIndex/performing-container-image-hardening',
      'Gabox301/SkillIndex/performing-container-security-scanning-with-trivy',
      'Gabox301/SkillIndex/performing-content-security-policy-bypass',
      'Gabox301/SkillIndex/performing-credential-access-with-lazagne',
      'Gabox301/SkillIndex/performing-cryptographic-audit-of-application',
      'Gabox301/SkillIndex/performing-csrf-attack-simulation',
      'Gabox301/SkillIndex/performing-cve-prioritization-with-kev-catalog',
      'Gabox301/SkillIndex/performing-dark-web-monitoring-for-threats',
      'Gabox301/SkillIndex/performing-deception-technology-deployment',
      'Gabox301/SkillIndex/performing-directory-traversal-testing',
      'Gabox301/SkillIndex/performing-disk-forensics-investigation',
      'Gabox301/SkillIndex/performing-dmarc-policy-enforcement-rollout',
      'Gabox301/SkillIndex/performing-dns-enumeration-and-zone-transfer',
      'Gabox301/SkillIndex/performing-dns-tunneling-detection',
      'Gabox301/SkillIndex/performing-docker-bench-security-assessment',
      'Gabox301/SkillIndex/performing-dynamic-analysis-of-android-app',
      'Gabox301/SkillIndex/performing-dynamic-analysis-with-any-run',
      'Gabox301/SkillIndex/performing-endpoint-forensics-investigation',
      'Gabox301/SkillIndex/performing-endpoint-vulnerability-remediation',
      'Gabox301/SkillIndex/performing-entitlement-review-with-sailpoint-iiq',
      'Gabox301/SkillIndex/performing-external-network-penetration-test',
      'Gabox301/SkillIndex/performing-false-positive-reduction-in-siem',
      'Gabox301/SkillIndex/performing-file-carving-with-foremost',
      'Gabox301/SkillIndex/performing-firmware-extraction-with-binwalk',
      'Gabox301/SkillIndex/performing-firmware-malware-analysis',
      'Gabox301/SkillIndex/performing-fuzzing-with-aflplusplus',
      'Gabox301/SkillIndex/performing-gcp-penetration-testing-with-gcpbucketbrute',
      'Gabox301/SkillIndex/performing-gcp-security-assessment-with-forseti',
      'Gabox301/SkillIndex/performing-graphql-depth-limit-attack',
      'Gabox301/SkillIndex/performing-graphql-introspection-attack',
      'Gabox301/SkillIndex/performing-graphql-security-assessment',
      'Gabox301/SkillIndex/performing-hardware-security-module-integration',
      'Gabox301/SkillIndex/performing-hash-cracking-with-hashcat',
      'Gabox301/SkillIndex/performing-http-parameter-pollution-attack',
      'Gabox301/SkillIndex/performing-ics-asset-discovery-with-claroty',
      'Gabox301/SkillIndex/performing-indicator-lifecycle-management',
      'Gabox301/SkillIndex/performing-initial-access-with-evilginx3',
      'Gabox301/SkillIndex/performing-insider-threat-investigation',
      'Gabox301/SkillIndex/performing-ioc-enrichment-automation',
      'Gabox301/SkillIndex/performing-ios-app-security-assessment',
      'Gabox301/SkillIndex/performing-iot-security-assessment',
      'Gabox301/SkillIndex/performing-ip-reputation-analysis-with-shodan',
      'Gabox301/SkillIndex/performing-jwt-none-algorithm-attack',
      'Gabox301/SkillIndex/performing-kerberoasting-attack',
      'Gabox301/SkillIndex/performing-kubernetes-cis-benchmark-with-kube-bench',
      'Gabox301/SkillIndex/performing-kubernetes-etcd-security-assessment',
      'Gabox301/SkillIndex/performing-kubernetes-penetration-testing',
      'Gabox301/SkillIndex/performing-lateral-movement-detection',
      'Gabox301/SkillIndex/performing-lateral-movement-with-wmiexec',
      'Gabox301/SkillIndex/performing-linux-log-forensics-investigation',
      'Gabox301/SkillIndex/performing-log-analysis-for-forensic-investigation',
      'Gabox301/SkillIndex/performing-log-source-onboarding-in-siem',
      'Gabox301/SkillIndex/performing-malware-hash-enrichment-with-virustotal',
      'Gabox301/SkillIndex/performing-malware-ioc-extraction',
      'Gabox301/SkillIndex/performing-malware-persistence-investigation',
      'Gabox301/SkillIndex/performing-malware-triage-with-yara',
      'Gabox301/SkillIndex/performing-memory-forensics-with-volatility3',
      'Gabox301/SkillIndex/performing-memory-forensics-with-volatility3-plugins',
      'Gabox301/SkillIndex/performing-mobile-app-certificate-pinning-bypass',
      'Gabox301/SkillIndex/performing-mobile-device-forensics-with-cellebrite',
      'Gabox301/SkillIndex/performing-network-forensics-with-wireshark',
      'Gabox301/SkillIndex/performing-network-packet-capture-analysis',
      'Gabox301/SkillIndex/performing-network-traffic-analysis-with-tshark',
      'Gabox301/SkillIndex/performing-network-traffic-analysis-with-zeek',
      'Gabox301/SkillIndex/performing-nist-csf-maturity-assessment',
      'Gabox301/SkillIndex/performing-oauth-scope-minimization-review',
      'Gabox301/SkillIndex/performing-oil-gas-cybersecurity-assessment',
      'Gabox301/SkillIndex/performing-open-source-intelligence-gathering',
      'Gabox301/SkillIndex/performing-osint-with-spiderfoot',
      'Gabox301/SkillIndex/performing-ot-network-security-assessment',
      'Gabox301/SkillIndex/performing-ot-vulnerability-assessment-with-claroty',
      'Gabox301/SkillIndex/performing-ot-vulnerability-scanning-safely',
      'Gabox301/SkillIndex/performing-packet-injection-attack',
      'Gabox301/SkillIndex/performing-paste-site-monitoring-for-credentials',
      'Gabox301/SkillIndex/performing-phishing-simulation-with-gophish',
      'Gabox301/SkillIndex/performing-physical-intrusion-assessment',
      'Gabox301/SkillIndex/performing-plc-firmware-security-analysis',
      'Gabox301/SkillIndex/performing-post-quantum-cryptography-migration',
      'Gabox301/SkillIndex/performing-power-grid-cybersecurity-assessment',
      'Gabox301/SkillIndex/performing-privacy-impact-assessment',
      'Gabox301/SkillIndex/performing-privilege-escalation-assessment',
      'Gabox301/SkillIndex/performing-privilege-escalation-on-linux',
      'Gabox301/SkillIndex/performing-privileged-account-access-review',
      'Gabox301/SkillIndex/performing-privileged-account-discovery',
      'Gabox301/SkillIndex/performing-purple-team-atomic-testing',
      'Gabox301/SkillIndex/performing-purple-team-exercise',
      'Gabox301/SkillIndex/performing-ransomware-response',
      'Gabox301/SkillIndex/performing-ransomware-tabletop-exercise',
      'Gabox301/SkillIndex/performing-red-team-phishing-with-gophish',
      'Gabox301/SkillIndex/performing-red-team-with-covenant',
      'Gabox301/SkillIndex/performing-s7comm-protocol-security-analysis',
      'Gabox301/SkillIndex/performing-sca-dependency-scanning-with-snyk',
      'Gabox301/SkillIndex/performing-scada-hmi-security-assessment',
      'Gabox301/SkillIndex/performing-second-order-sql-injection',
      'Gabox301/SkillIndex/performing-security-headers-audit',
      'Gabox301/SkillIndex/performing-serverless-function-security-review',
      'Gabox301/SkillIndex/performing-service-account-audit',
      'Gabox301/SkillIndex/performing-service-account-credential-rotation',
      'Gabox301/SkillIndex/performing-soap-web-service-security-testing',
      'Gabox301/SkillIndex/performing-soc-tabletop-exercise',
      'Gabox301/SkillIndex/performing-soc2-type2-audit-preparation',
      'Gabox301/SkillIndex/performing-sqlite-database-forensics',
      'Gabox301/SkillIndex/performing-ssl-certificate-lifecycle-management',
      'Gabox301/SkillIndex/performing-ssl-stripping-attack',
      'Gabox301/SkillIndex/performing-ssl-tls-inspection-configuration',
      'Gabox301/SkillIndex/performing-ssl-tls-security-assessment',
      'Gabox301/SkillIndex/performing-ssrf-vulnerability-exploitation',
      'Gabox301/SkillIndex/performing-static-malware-analysis-with-pe-studio',
      'Gabox301/SkillIndex/performing-steganography-detection',
      'Gabox301/SkillIndex/performing-subdomain-enumeration-with-subfinder',
      'Gabox301/SkillIndex/performing-supply-chain-attack-simulation',
      'Gabox301/SkillIndex/performing-thick-client-application-penetration-test',
      'Gabox301/SkillIndex/performing-threat-emulation-with-atomic-red-team',
      'Gabox301/SkillIndex/performing-threat-hunting-with-elastic-siem',
      'Gabox301/SkillIndex/performing-threat-hunting-with-yara-rules',
      'Gabox301/SkillIndex/performing-threat-intelligence-sharing-with-misp',
      'Gabox301/SkillIndex/performing-threat-landscape-assessment-for-sector',
      'Gabox301/SkillIndex/performing-threat-modeling-with-owasp-threat-dragon',
      'Gabox301/SkillIndex/performing-timeline-reconstruction-with-plaso',
      'Gabox301/SkillIndex/performing-user-behavior-analytics',
      'Gabox301/SkillIndex/performing-vlan-hopping-attack',
      'Gabox301/SkillIndex/performing-vulnerability-scanning-with-nessus',
      'Gabox301/SkillIndex/performing-web-application-firewall-bypass',
      'Gabox301/SkillIndex/performing-web-application-penetration-test',
      'Gabox301/SkillIndex/performing-web-application-scanning-with-nikto',
      'Gabox301/SkillIndex/performing-web-application-vulnerability-triage',
      'Gabox301/SkillIndex/performing-web-cache-deception-attack',
      'Gabox301/SkillIndex/performing-web-cache-poisoning-attack',
      'Gabox301/SkillIndex/performing-wifi-password-cracking-with-aircrack',
      'Gabox301/SkillIndex/performing-windows-artifact-analysis-with-eric-zimmerman-tools',
      'Gabox301/SkillIndex/performing-wireless-network-penetration-test',
      'Gabox301/SkillIndex/performing-wireless-security-assessment-with-kismet',
      'Gabox301/SkillIndex/performing-yara-rule-development-for-detection',
    ],
  },    {
    id: 'orphan-building',
    name: 'Building Skills',
    detect: {},
    skills: [
      'Gabox301/SkillIndex/building-adversary-infrastructure-tracking-system',
      'Gabox301/SkillIndex/building-attack-pattern-library-from-cti-reports',
      'Gabox301/SkillIndex/building-automated-malware-submission-pipeline',
      'Gabox301/SkillIndex/building-c2-infrastructure-with-sliver-framework',
      'Gabox301/SkillIndex/building-c2-redirector-infrastructure',
      'Gabox301/SkillIndex/building-cloud-siem-with-sentinel',
      'Gabox301/SkillIndex/building-detection-rule-with-splunk-spl',
      'Gabox301/SkillIndex/building-detection-rules-with-sigma',
      'Gabox301/SkillIndex/building-devsecops-pipeline-with-gitlab-ci',
      'Gabox301/SkillIndex/building-identity-federation-with-saml-azure-ad',
      'Gabox301/SkillIndex/building-identity-governance-lifecycle-process',
      'Gabox301/SkillIndex/building-incident-response-dashboard',
      'Gabox301/SkillIndex/building-incident-response-playbook',
      'Gabox301/SkillIndex/building-incident-timeline-with-timesketch',
      'Gabox301/SkillIndex/building-ioc-defanging-and-sharing-pipeline',
      'Gabox301/SkillIndex/building-ioc-enrichment-pipeline-with-opencti',
      'Gabox301/SkillIndex/building-malware-incident-communication-template',
      'Gabox301/SkillIndex/building-patch-tuesday-response-process',
      'Gabox301/SkillIndex/building-phishing-reporting-button-workflow',
      'Gabox301/SkillIndex/building-ransomware-playbook-with-cisa-framework',
      'Gabox301/SkillIndex/building-red-team-c2-infrastructure-with-havoc',
      'Gabox301/SkillIndex/building-role-mining-for-rbac-optimization',
      'Gabox301/SkillIndex/building-soc-escalation-matrix',
      'Gabox301/SkillIndex/building-soc-metrics-and-kpi-tracking',
      'Gabox301/SkillIndex/building-soc-playbook-for-ransomware',
      'Gabox301/SkillIndex/building-super-timelines-with-plaso',
      'Gabox301/SkillIndex/building-threat-actor-profile-from-osint',
      'Gabox301/SkillIndex/building-threat-feed-aggregation-with-misp',
      'Gabox301/SkillIndex/building-threat-hunt-hypothesis-framework',
      'Gabox301/SkillIndex/building-threat-intelligence-enrichment-in-splunk',
      'Gabox301/SkillIndex/building-threat-intelligence-feed-integration',
      'Gabox301/SkillIndex/building-threat-intelligence-platform',
      'Gabox301/SkillIndex/building-vulnerability-aging-and-sla-tracking',
      'Gabox301/SkillIndex/building-vulnerability-dashboard-with-defectdojo',
      'Gabox301/SkillIndex/building-vulnerability-exception-tracking-system',
      'Gabox301/SkillIndex/building-vulnerability-scanning-workflow',
    ],
  },
{
    id: 'orphan-exploiting',
    name: 'Exploiting Skills',
    detect: {},
    skills: [
      'Gabox301/SkillIndex/exploiting-active-directory-certificate-services-esc1',
      'Gabox301/SkillIndex/exploiting-active-directory-with-bloodhound',
      'Gabox301/SkillIndex/exploiting-adcs-with-certipy',
      'Gabox301/SkillIndex/exploiting-api-injection-vulnerabilities',
      'Gabox301/SkillIndex/exploiting-bgp-hijacking-vulnerabilities',
      'Gabox301/SkillIndex/exploiting-broken-function-level-authorization',
      'Gabox301/SkillIndex/exploiting-broken-link-hijacking',
      'Gabox301/SkillIndex/exploiting-constrained-delegation-abuse',
      'Gabox301/SkillIndex/exploiting-deeplink-vulnerabilities',
      'Gabox301/SkillIndex/exploiting-excessive-data-exposure-in-api',
      'Gabox301/SkillIndex/exploiting-http-request-smuggling',
      'Gabox301/SkillIndex/exploiting-idor-vulnerabilities',
      'Gabox301/SkillIndex/exploiting-insecure-data-storage-in-mobile',
      'Gabox301/SkillIndex/exploiting-insecure-deserialization',
      'Gabox301/SkillIndex/exploiting-ipv6-vulnerabilities',
      'Gabox301/SkillIndex/exploiting-jwt-algorithm-confusion-attack',
      'Gabox301/SkillIndex/exploiting-kerberoasting-with-impacket',
      'Gabox301/SkillIndex/exploiting-mass-assignment-in-rest-apis',
      'Gabox301/SkillIndex/exploiting-ms17-010-eternalblue-vulnerability',
      'Gabox301/SkillIndex/exploiting-nopac-cve-2021-42278-42287',
      'Gabox301/SkillIndex/exploiting-nosql-injection-vulnerabilities',
      'Gabox301/SkillIndex/exploiting-oauth-misconfiguration',
      'Gabox301/SkillIndex/exploiting-prototype-pollution-in-javascript',
      'Gabox301/SkillIndex/exploiting-race-condition-vulnerabilities',
      'Gabox301/SkillIndex/exploiting-server-side-request-forgery',
      'Gabox301/SkillIndex/exploiting-smb-vulnerabilities-with-metasploit',
      'Gabox301/SkillIndex/exploiting-sql-injection-vulnerabilities',
      'Gabox301/SkillIndex/exploiting-sql-injection-with-sqlmap',
      'Gabox301/SkillIndex/exploiting-template-injection-vulnerabilities',
      'Gabox301/SkillIndex/exploiting-type-juggling-vulnerabilities',
      'Gabox301/SkillIndex/exploiting-vulnerabilities-with-metasploit-framework',
      'Gabox301/SkillIndex/exploiting-websocket-vulnerabilities',
      'Gabox301/SkillIndex/exploiting-zerologon-vulnerability-cve-2020-1472',
    ],
  },
  {
    id: 'orphan-testing',
    name: 'Testing Skills',
    detect: {},
    skills: [
      'Gabox301/SkillIndex/testing-android-intents-for-vulnerabilities',
      'Gabox301/SkillIndex/testing-api-authentication-weaknesses',
      'Gabox301/SkillIndex/testing-api-for-broken-object-level-authorization',
      'Gabox301/SkillIndex/testing-api-for-mass-assignment-vulnerability',
      'Gabox301/SkillIndex/testing-api-security-with-owasp-top-10',
      'Gabox301/SkillIndex/testing-cors-misconfiguration',
      'Gabox301/SkillIndex/testing-for-broken-access-control',
      'Gabox301/SkillIndex/testing-for-business-logic-vulnerabilities',
      'Gabox301/SkillIndex/testing-for-email-header-injection',
      'Gabox301/SkillIndex/testing-for-host-header-injection',
      'Gabox301/SkillIndex/testing-for-json-web-token-vulnerabilities',
      'Gabox301/SkillIndex/testing-for-open-redirect-vulnerabilities',
      'Gabox301/SkillIndex/testing-for-sensitive-data-exposure',
      'Gabox301/SkillIndex/testing-for-system-prompt-leakage',
      'Gabox301/SkillIndex/testing-for-xml-injection-vulnerabilities',
      'Gabox301/SkillIndex/testing-for-xss-vulnerabilities',
      'Gabox301/SkillIndex/testing-for-xss-vulnerabilities-with-burpsuite',
      'Gabox301/SkillIndex/testing-for-xxe-injection-vulnerabilities',
      'Gabox301/SkillIndex/testing-jwt-token-security',
      'Gabox301/SkillIndex/testing-mobile-api-authentication',
      'Gabox301/SkillIndex/testing-oauth2-implementation-flaws',
      'Gabox301/SkillIndex/testing-prompt-injection-in-rag-pipelines',
      'Gabox301/SkillIndex/testing-ransomware-recovery-procedures',
      'Gabox301/SkillIndex/testing-websocket-api-security',
    ],
  },
  {
    id: 'orphan-conducting',
    name: 'Conducting Skills',
    detect: {},
    skills: [
      'Gabox301/SkillIndex/conducting-api-security-testing',
      'Gabox301/SkillIndex/conducting-cloud-incident-response',
      'Gabox301/SkillIndex/conducting-cloud-penetration-testing',
      'Gabox301/SkillIndex/conducting-cyber-risk-assessment-with-nist-800-30',
      'Gabox301/SkillIndex/conducting-domain-persistence-with-dcsync',
      'Gabox301/SkillIndex/conducting-external-reconnaissance-with-osint',
      'Gabox301/SkillIndex/conducting-full-scope-red-team-engagement',
      'Gabox301/SkillIndex/conducting-internal-network-penetration-test',
      'Gabox301/SkillIndex/conducting-internal-reconnaissance-with-bloodhound-ce',
      'Gabox301/SkillIndex/conducting-malware-incident-response',
      'Gabox301/SkillIndex/conducting-man-in-the-middle-attack-simulation',
      'Gabox301/SkillIndex/conducting-memory-forensics-with-volatility',
      'Gabox301/SkillIndex/conducting-mobile-app-penetration-test',
      'Gabox301/SkillIndex/conducting-network-penetration-test',
      'Gabox301/SkillIndex/conducting-pass-the-ticket-attack',
      'Gabox301/SkillIndex/conducting-phishing-incident-response',
      'Gabox301/SkillIndex/conducting-post-incident-lessons-learned',
      'Gabox301/SkillIndex/conducting-social-engineering-penetration-test',
      'Gabox301/SkillIndex/conducting-social-engineering-pretext-call',
      'Gabox301/SkillIndex/conducting-spearphishing-simulation-campaign',
      'Gabox301/SkillIndex/conducting-wireless-network-penetration-test',
    ],
  },
  {
    id: 'orphan-configuring',
    name: 'Configuring Skills',
    detect: {},
    skills: [
      'Gabox301/SkillIndex/configuring-active-directory-tiered-model',
      'Gabox301/SkillIndex/configuring-certificate-authority-with-openssl',
      'Gabox301/SkillIndex/configuring-host-based-intrusion-detection',
      'Gabox301/SkillIndex/configuring-hsm-for-key-storage',
      'Gabox301/SkillIndex/configuring-identity-aware-proxy-with-google-iap',
      'Gabox301/SkillIndex/configuring-ldap-security-hardening',
      'Gabox301/SkillIndex/configuring-microsegmentation-for-zero-trust',
      'Gabox301/SkillIndex/configuring-multi-factor-authentication-with-duo',
      'Gabox301/SkillIndex/configuring-network-segmentation-with-vlans',
      'Gabox301/SkillIndex/configuring-oauth2-authorization-flow',
      'Gabox301/SkillIndex/configuring-pfsense-firewall-rules',
      'Gabox301/SkillIndex/configuring-snort-ids-for-intrusion-detection',
      'Gabox301/SkillIndex/configuring-suricata-for-network-monitoring',
      'Gabox301/SkillIndex/configuring-tls-1-3-for-secure-communications',
      'Gabox301/SkillIndex/configuring-windows-defender-advanced-settings',
      'Gabox301/SkillIndex/configuring-windows-event-logging-for-detection',
      'Gabox301/SkillIndex/configuring-zscaler-private-access-for-ztna',
    ],
  },
  {
    id: 'orphan-securing',
    name: 'Securing Skills',
    detect: {},
    skills: [
      'Gabox301/SkillIndex/securing-agentic-ai-tool-invocation',
      'Gabox301/SkillIndex/securing-azure-with-microsoft-defender',
      'Gabox301/SkillIndex/securing-container-registry-images',
      'Gabox301/SkillIndex/securing-container-registry-with-harbor',
      'Gabox301/SkillIndex/securing-github-actions-workflows',
      'Gabox301/SkillIndex/securing-helm-chart-deployments',
      'Gabox301/SkillIndex/securing-historian-server-in-ot-environment',
      'Gabox301/SkillIndex/securing-kubernetes-on-cloud',
      'Gabox301/SkillIndex/securing-remote-access-to-ot-environment',
      'Gabox301/SkillIndex/securing-serverless-functions',
    ],
  },
  {
    id: 'orphan-auditing',
    name: 'Auditing Skills',
    detect: {},
    skills: [
      'Gabox301/SkillIndex/auditing-azure-active-directory-configuration',
      'Gabox301/SkillIndex/auditing-cloud-with-cis-benchmarks',
      'Gabox301/SkillIndex/auditing-entra-id-with-aadinternals',
      'Gabox301/SkillIndex/auditing-foundry-smart-contract-security',
      'Gabox301/SkillIndex/auditing-gcp-iam-permissions',
      'Gabox301/SkillIndex/auditing-kubernetes-cluster-rbac',
      'Gabox301/SkillIndex/auditing-kubernetes-rbac-privilege-escalation',
      'Gabox301/SkillIndex/auditing-mcp-servers-for-tool-poisoning',
      'Gabox301/SkillIndex/auditing-terraform-infrastructure-for-security',
      'Gabox301/SkillIndex/auditing-tls-certificate-transparency-logs',
      'Gabox301/SkillIndex/auditing-uefi-firmware-with-chipsec',
    ],
  },
  {
    id: 'orphan-deploying',
    name: 'Deploying Skills',
    detect: {},
    skills: [
      'Gabox301/SkillIndex/deploying-active-directory-honeytokens',
      'Gabox301/SkillIndex/deploying-cloud-deception-with-decoy-resources',
      'Gabox301/SkillIndex/deploying-cloudflare-access-for-zero-trust',
      'Gabox301/SkillIndex/deploying-decoy-files-for-ransomware-detection',
      'Gabox301/SkillIndex/deploying-edr-agent-with-crowdstrike',
      'Gabox301/SkillIndex/deploying-honeytokens-and-canarytokens',
      'Gabox301/SkillIndex/deploying-osquery-for-endpoint-monitoring',
      'Gabox301/SkillIndex/deploying-palo-alto-prisma-access-zero-trust',
      'Gabox301/SkillIndex/deploying-ransomware-canary-files',
      'Gabox301/SkillIndex/deploying-software-defined-perimeter',
      'Gabox301/SkillIndex/deploying-tailscale-for-zero-trust-vpn',
    ],
  },
  {
    id: 'orphan-sdd',
    name: 'Sdd Skills',
    detect: {},
    skills: [
      'Gabox301/SkillIndex/sdd-apply',
      'Gabox301/SkillIndex/sdd-archive',
      'Gabox301/SkillIndex/sdd-design',
      'Gabox301/SkillIndex/sdd-explore',
      'Gabox301/SkillIndex/sdd-init',
      'Gabox301/SkillIndex/sdd-onboard',
      'Gabox301/SkillIndex/sdd-propose',
      'Gabox301/SkillIndex/sdd-spec',
      'Gabox301/SkillIndex/sdd-tasks',
      'Gabox301/SkillIndex/sdd-verify',
    ],
  },
  {
    id: 'orphan-scanning',
    name: 'Scanning Skills',
    detect: {},
    skills: [
      'Gabox301/SkillIndex/scanning-container-images-with-grype',
      'Gabox301/SkillIndex/scanning-containers-with-trivy-in-cicd',
      'Gabox301/SkillIndex/scanning-docker-images-with-trivy',
      'Gabox301/SkillIndex/scanning-iac-and-images-with-trivy',
      'Gabox301/SkillIndex/scanning-infrastructure-with-nessus',
      'Gabox301/SkillIndex/scanning-kubernetes-manifests-with-kubesec',
      'Gabox301/SkillIndex/scanning-network-with-nmap-advanced',
    ],
  },
  {
    id: 'orphan-appwrite',
    name: 'Appwrite Skills',
    detect: {},
    skills: [
      'Gabox301/SkillIndex/appwrite-cli',
      'Gabox301/SkillIndex/appwrite-go',
      'Gabox301/SkillIndex/appwrite-python',
      'Gabox301/SkillIndex/appwrite-ruby',
      'Gabox301/SkillIndex/appwrite-rust',
      'Gabox301/SkillIndex/appwrite-typescript',
    ],
  },
  {
    id: 'orphan-extracting',
    name: 'Extracting Skills',
    detect: {},
    skills: [
      'Gabox301/SkillIndex/extracting-browser-history-artifacts',
      'Gabox301/SkillIndex/extracting-config-from-agent-tesla-rat',
      'Gabox301/SkillIndex/extracting-credentials-from-memory-dump',
      'Gabox301/SkillIndex/extracting-iocs-from-malware-samples',
      'Gabox301/SkillIndex/extracting-memory-artifacts-with-rekall',
      'Gabox301/SkillIndex/extracting-windows-event-logs-artifacts',
    ],
  },
  {
    id: 'orphan-reverse',
    name: 'Reverse Skills',
    detect: {},
    skills: [
      'Gabox301/SkillIndex/reverse-engineering-android-malware-with-jadx',
      'Gabox301/SkillIndex/reverse-engineering-dotnet-malware-with-dnspy',
      'Gabox301/SkillIndex/reverse-engineering-ios-app-with-frida',
      'Gabox301/SkillIndex/reverse-engineering-malware-with-ghidra',
      'Gabox301/SkillIndex/reverse-engineering-ransomware-encryption-routine',
      'Gabox301/SkillIndex/reverse-engineering-rust-malware',
    ],
  },
  {
    id: 'orphan-executing',
    name: 'Executing Skills',
    detect: {},
    skills: [
      'Gabox301/SkillIndex/executing-active-directory-attack-simulation',
      'Gabox301/SkillIndex/executing-nist-rmf-authorization-to-operate',
      'Gabox301/SkillIndex/executing-phishing-simulation-campaign',
      'Gabox301/SkillIndex/executing-red-team-engagement-planning',
      'Gabox301/SkillIndex/executing-red-team-exercise',
    ],
  },
  {
    id: 'orphan-triaging',
    name: 'Triaging Skills',
    detect: {},
    skills: [
      'Gabox301/SkillIndex/triaging-security-alerts-in-splunk',
      'Gabox301/SkillIndex/triaging-security-incident',
      'Gabox301/SkillIndex/triaging-security-incident-with-ir-playbook',
      'Gabox301/SkillIndex/triaging-vulnerabilities-with-ssvc-framework',
      'Gabox301/SkillIndex/triaging-windows-with-kape',
    ],
  },
  {
    id: 'orphan-misc',
    name: 'Miscellaneous Orphan Skills',
    detect: {},
    skills: [
      'Gabox301/SkillIndex/abusing-dpapi-for-credential-access',
      'Gabox301/SkillIndex/abusing-shadow-credentials-for-privesc',
      'Gabox301/SkillIndex/achieving-cmmc-level-2-compliance',
      'Gabox301/SkillIndex/acquiring-disk-image-with-dd-and-dcfldd',
      'Gabox301/SkillIndex/assessing-vector-and-embedding-weaknesses',
      'Gabox301/SkillIndex/attacking-entra-id-with-roadtools',
      'Gabox301/SkillIndex/attacking-oauth-with-device-code-phishing',
      'Gabox301/SkillIndex/automating-ioc-enrichment',
      'Gabox301/SkillIndex/benchmarking-kubernetes-with-kube-bench',
      'Gabox301/SkillIndex/branch-pr',
      'Gabox301/SkillIndex/bypassing-authentication-with-forced-browsing',
      'Gabox301/SkillIndex/chained-pr',
      'Gabox301/SkillIndex/coercing-authentication-with-coercer-petitpotam',
      'Gabox301/SkillIndex/cognitive-doc-design',
      'Gabox301/SkillIndex/collecting-indicators-of-compromise',
      'Gabox301/SkillIndex/collecting-open-source-intelligence',
      'Gabox301/SkillIndex/collecting-threat-intelligence-with-misp',
      'Gabox301/SkillIndex/collecting-volatile-evidence-from-compromised-host',
      'Gabox301/SkillIndex/comment-writer',
      'Gabox301/SkillIndex/containing-active-breach',
      'Gabox301/SkillIndex/continuous-llm-red-teaming-with-promptfoo',
      'Gabox301/SkillIndex/copywriting',
      'Gabox301/SkillIndex/correlating-security-events-in-qradar',
      'Gabox301/SkillIndex/correlating-threat-campaigns',
      'Gabox301/SkillIndex/defending-llms-with-guardrails',
      'Gabox301/SkillIndex/deobfuscating-javascript-malware',
      'Gabox301/SkillIndex/deobfuscating-powershell-obfuscated-malware',
      'Gabox301/SkillIndex/designing-adversary-engagement-with-mitre-engage',
      'Gabox301/SkillIndex/emulating-cloud-attacks-with-stratus-red-team',
      'Gabox301/SkillIndex/enumerating-cloud-with-cloudfox',
      'Gabox301/SkillIndex/eradicating-malware-from-infected-systems',
      'Gabox301/SkillIndex/escaping-containers-to-host',
      'Gabox301/SkillIndex/evaluating-threat-intelligence-platforms',
      'Gabox301/SkillIndex/find-skills',
      'Gabox301/SkillIndex/fleet-hunting-with-velociraptor',
      'Gabox301/SkillIndex/generating-and-analyzing-sboms',
      'Gabox301/SkillIndex/generating-forensic-timelines-with-hayabusa',
      'Gabox301/SkillIndex/generating-threat-intelligence-reports',
      'Gabox301/SkillIndex/gentle-ai-bench',
      'Gabox301/SkillIndex/go-testing',
      'Gabox301/SkillIndex/graphify',
      'Gabox301/SkillIndex/hardening-docker-containers-for-production',
      'Gabox301/SkillIndex/hardening-docker-daemon-configuration',
      'Gabox301/SkillIndex/hardening-linux-endpoint-with-cis-benchmark',
      'Gabox301/SkillIndex/hardening-windows-endpoint-with-cis-benchmark',
      'Gabox301/SkillIndex/integrating-dast-with-owasp-zap-in-pipeline',
      'Gabox301/SkillIndex/integrating-sast-into-github-actions-pipeline',
      'Gabox301/SkillIndex/intercepting-mobile-traffic-with-burpsuite',
      'Gabox301/SkillIndex/investigating-insider-threat-indicators',
      'Gabox301/SkillIndex/investigating-phishing-email-incident',
      'Gabox301/SkillIndex/investigating-ransomware-attack-artifacts',
      'Gabox301/SkillIndex/issue-creation',
      'Gabox301/SkillIndex/judgment-day',
      'Gabox301/SkillIndex/managing-cloud-identity-with-okta',
      'Gabox301/SkillIndex/managing-intelligence-lifecycle',
      'Gabox301/SkillIndex/managing-third-party-vendor-risk',
      'Gabox301/SkillIndex/mapping-attack-paths-with-bloodhound-ce',
      'Gabox301/SkillIndex/mapping-mitre-attack-techniques',
      'Gabox301/SkillIndex/migrating-to-post-quantum-cryptography',
      'Gabox301/SkillIndex/modeling-threats-with-opencti',
      'Gabox301/SkillIndex/monitoring-darkweb-sources',
      'Gabox301/SkillIndex/monitoring-scada-modbus-traffic-anomalies',
      'Gabox301/SkillIndex/moving-laterally-with-netexec',
      'Gabox301/SkillIndex/operating-havoc-c2',
      'Gabox301/SkillIndex/operating-sliver-c2',
      'Gabox301/SkillIndex/operationalizing-misp-threat-feeds',
      'Gabox301/SkillIndex/orchestrating-llm-attacks-with-pyrit',
      'Gabox301/SkillIndex/parsing-artifacts-with-eric-zimmerman-tools',
      'Gabox301/SkillIndex/post-exploiting-microsoft-graph-with-graphrunner',
      'Gabox301/SkillIndex/prioritizing-vulnerabilities-with-cvss-scoring',
      'Gabox301/SkillIndex/processing-stix-taxii-feeds',
      'Gabox301/SkillIndex/profiling-threat-actor-groups',
      'Gabox301/SkillIndex/rdd-defect-workflow',
      'Gabox301/SkillIndex/recovering-deleted-files-with-photorec',
      'Gabox301/SkillIndex/recovering-from-ransomware-attack',
      'Gabox301/SkillIndex/red-teaming-llms-with-garak',
      'Gabox301/SkillIndex/relaying-ntlm-for-adcs-esc8',
      'Gabox301/SkillIndex/remediating-s3-bucket-misconfiguration',
      'Gabox301/SkillIndex/skill-creator',
      'Gabox301/SkillIndex/skill-improver',
      'Gabox301/SkillIndex/skill-registry',
      'Gabox301/SkillIndex/supabase',
      'Gabox301/SkillIndex/systemic-issue-triage',
      'Gabox301/SkillIndex/tracking-threat-actor-infrastructure',
      'Gabox301/SkillIndex/validating-backup-integrity-for-recovery',
      'Gabox301/SkillIndex/validating-tpm-measured-boot-attestation',
      'Gabox301/SkillIndex/vercel-react-best-practices',
      'Gabox301/SkillIndex/verifying-build-provenance-with-slsa-sigstore',
      'Gabox301/SkillIndex/web-design-guidelines',
      'Gabox301/SkillIndex/work-unit-commits',
    ],
  },
  {
    id: 'mattpocock-skills',
    name: 'Matt Pocock Skills',
    detect: {},
    skills: [
      'mattpocock/skills/setup-matt-pocock-skills',
      'mattpocock/skills/grilling',
      'mattpocock/skills/teach',
      'mattpocock/skills/grill-me',
      'mattpocock/skills/grill-with-docs',
      'mattpocock/skills/improve-codebase-architecture',
      'mattpocock/skills/tdd',
    ],
  },
  {
    id: 'taste-skill',
    name: 'Taste Skill',
    detect: {},
    skills: ['Leonxlnx/taste-skill/taste-skill'],
  },
  {
    id: 'archify',
    name: 'Archify',
    detect: {},
    skills: ['tt-a1i/archify/archify'],
  },
];
// ── Combo Skills Map (cross-technology) ──────────────────────
export const COMBO_SKILLS_MAP: ComboSkill[] = [
  {
    id: 'expo-tailwind',
    name: 'Expo + Tailwind CSS',
    requires: ['expo', 'tailwind'],
    skills: ['expo/skills/expo-tailwind-setup'],
  },
  {
    id: 'react-hook-form-zod',
    name: 'React Hook Form + Zod',
    requires: ['react-hook-form', 'zod'],
    skills: ['pproenca/dot-skills/zod'],
  },
  {
    id: 'nextjs-supabase',
    name: 'Next.js + Supabase',
    requires: ['nextjs', 'supabase'],
    skills: ['supabase/agent-skills/supabase-postgres-best-practices'],
  },
  {
    id: 'react-native-expo',
    name: 'React Native + Expo',
    requires: ['react-native', 'expo'],
    skills: ['expo/skills/building-native-ui', 'sleekdotdesign/agent-skills/design-mobile-apps'],
  },
  {
    id: 'nextjs-vercel-ai',
    name: 'Next.js + Vercel AI SDK',
    requires: ['nextjs', 'vercel-ai'],
    skills: ['vercel/ai/use-ai-sdk', 'vercel-labs/next-skills/next-best-practices'],
  },
  {
    id: 'nextjs-playwright',
    name: 'Next.js + Playwright',
    requires: ['nextjs', 'playwright'],
    skills: ['currents-dev/playwright-best-practices-skill/playwright-best-practices'],
  },
  {
    id: 'react-shadcn',
    name: 'React + shadcn/ui',
    requires: ['react', 'shadcn'],
    skills: ['shadcn/ui/shadcn', 'vercel-labs/agent-skills/react-best-practices'],
  },
  {
    id: 'tailwind-shadcn',
    name: 'Tailwind CSS + shadcn/ui',
    requires: ['tailwind', 'shadcn'],
    skills: ['secondsky/claude-skills/tailwind-v4-shadcn'],
  },
  {
    id: 'gsap-react',
    name: 'GSAP + React',
    requires: ['gsap', 'react'],
    skills: ['greensock/gsap-skills/gsap-react'],
  },
  {
    id: 'cloudflare-vite',
    name: 'Cloudflare + Vite',
    requires: ['cloudflare', 'vite'],
    skills: ['cloudflare/vinext/migrate-to-vinext'],
  },
  {
    id: 'node-express',
    name: 'Node.js + Express',
    requires: ['node', 'express'],
    skills: ['aj-geddes/useful-ai-prompts/nodejs-express-server'],
  },
  {
    id: 'nextjs-clerk',
    name: 'Next.js + Clerk',
    requires: ['nextjs', 'clerk'],
    skills: ['clerk/skills/clerk-nextjs-patterns'],
  },
  {
    id: 'nuxt-clerk',
    name: 'Nuxt + Clerk',
    requires: ['nuxt', 'clerk'],
    skills: ['clerk/skills/clerk-nuxt-patterns'],
  },
  {
    id: 'vue-clerk',
    name: 'Vue + Clerk',
    requires: ['vue', 'clerk'],
    skills: ['clerk/skills/clerk-vue-patterns'],
  },
  {
    id: 'react-clerk',
    name: 'React + Clerk',
    requires: ['react', 'clerk'],
    skills: ['clerk/skills/clerk-react-patterns'],
  },
  {
    id: 'astro-clerk',
    name: 'Astro + Clerk',
    requires: ['astro', 'clerk'],
    skills: ['clerk/skills/clerk-astro-patterns'],
  },
  {
    id: 'expo-clerk',
    name: 'Expo + Clerk',
    requires: ['expo', 'clerk'],
    skills: ['clerk/skills/clerk-expo-patterns'],
  },
  {
    id: 'react-react-three-fiber',
    name: 'React + React Three Fiber',
    requires: ['threejs', 'react', '@react-three/fiber'],
    skills: ['vercel-labs/json-render/react-three-fiber'],
  },
  {
    id: 'react-router-clerk',
    name: 'React Router + Clerk',
    requires: ['react-router', 'clerk'],
    skills: ['clerk/skills/clerk-react-router-patterns', 'clerk/skills/clerk-setup', 'clerk/skills/clerk'],
  },
  {
    id: 'tanstack-clerk',
    name: 'TanStack Start + Clerk',
    requires: ['tanstack-start', 'clerk'],
    skills: ['clerk/skills/clerk-tanstack-patterns', 'clerk/skills/clerk-setup', 'clerk/skills/clerk'],
  },
  {
    id: 'chrome-extension-clerk',
    name: 'Chrome Extension + Clerk',
    requires: ['chrome-extension', 'clerk'],
    skills: ['clerk/skills/clerk-chrome-extension-patterns', 'clerk/skills/clerk-setup', 'clerk/skills/clerk'],
  },
  {
    id: 'swiftui-clerk',
    name: 'SwiftUI + Clerk',
    requires: ['swiftui', 'clerk'],
    skills: ['clerk/skills/clerk-swift', 'clerk/skills/clerk-setup', 'clerk/skills/clerk'],
  },
  {
    id: 'android-clerk',
    name: 'Android + Clerk',
    requires: ['android', 'clerk'],
    skills: ['clerk/skills/clerk-android', 'clerk/skills/clerk-setup', 'clerk/skills/clerk'],
  },
  {
    id: 'rails-rspec',
    name: 'Ruby on Rails + RSpec',
    requires: ['rails', 'rspec'],
    skills: ['igmarin/rails-agent-skills/rails-tdd-slices', 'igmarin/rails-agent-skills/rails-bug-triage'],
  },
  {
    id: 'rails-sidekiq',
    name: 'Ruby on Rails + Sidekiq',
    requires: ['rails', 'sidekiq'],
    skills: [],
  },
  securityOperationsCombo,
  redTeamCombo,
  cloudSecurityCombo,
  forensicsIrCombo,
];
// ── Frontend Detection ────────────────────────────────────────
export const FRONTEND_PACKAGES: Set<string> = new Set([
  'react',
  'vue',
  'svelte',
  'astro',
  'next',
  '@angular/core',
  'solid-js',
  'lit',
  'preact',
  'nuxt',
  '@sveltejs/kit',
]);
export const FRONTEND_BONUS_SKILLS: string[] = [
  'anthropics/skills/frontend-design',
  'addyosmani/web-quality-skills/accessibility',
  'addyosmani/web-quality-skills/seo',
];
// ── Agent Folder Map ─────────────────────────────────────────
export const AGENT_FOLDER_MAP: Record<string, string> = {
  '.claude': 'claude-code',
  '.cline': 'cline',
  '.junie': 'junie',
  '.codebuddy': 'codebuddy',
  '.continue': 'continue',
  '.kiro': 'kiro-cli',
  '.opencode': 'opencode',
  '.cursor': 'cursor',
};
export const WEB_FRONTEND_EXTENSIONS: Set<string> = new Set([
  '.html',
  '.htm',
  '.css',
  '.scss',
  '.sass',
  '.less',
  '.vue',
  '.svelte',
  '.jsx',
  '.tsx',
  '.twig',
  '.tpl',
  '.ejs',
  '.hbs',
  '.pug',
  '.njk',
]);
