use crate::skills::types::{DetectConfig, Technology};

pub const MATTPOCOCK_SKILLS_TECH: Technology = Technology {
    id: "mattpocock-skills",
    name: "Matt Pocock Skills",
    detect: DetectConfig {
        packages: &[],
        package_patterns: &[],
        config_files: &[],
        file_extensions: &[],
        gems: &[],
        config_file_content: &[],
    },
    skills: &[
        "mattpocock/skills/setup-matt-pocock-skills",
        "mattpocock/skills/grilling",
        "mattpocock/skills/teach",
        "mattpocock/skills/grill-me",
        "mattpocock/skills/grill-with-docs",
        "mattpocock/skills/improve-codebase-architecture",
        "mattpocock/skills/tdd",
        "mattpocock/skills/ask-matt",
        "mattpocock/skills/codebase-design",
        "mattpocock/skills/code-review",
        "mattpocock/skills/diagnosing-bugs",
        "mattpocock/skills/domain-modeling",
        "mattpocock/skills/prototype",
        "mattpocock/skills/research",
        "mattpocock/skills/resolving-merge-conflicts",
        "mattpocock/skills/triage",
        "mattpocock/skills/to-spec",
        "mattpocock/skills/to-tickets",
        "mattpocock/skills/implement",
        "mattpocock/skills/wayfinder",
        "mattpocock/skills/wizard",
        "mattpocock/skills/claude-handoff",
        "mattpocock/skills/implement-spec",
        "mattpocock/skills/loop-me",
        "mattpocock/skills/retro",
        "mattpocock/skills/setup-ts-deep-modules",
        "mattpocock/skills/writing-beats",
        "mattpocock/skills/writing-fragments",
        "mattpocock/skills/writing-shape",
        "mattpocock/skills/git-guardrails-claude-code",
        "mattpocock/skills/migrate-to-shoehorn",
        "mattpocock/skills/scaffold-exercises",
        "mattpocock/skills/setup-pre-commit",
        "mattpocock/skills/handoff",
        "mattpocock/skills/to-questionnaire",
        "mattpocock/skills/wait-what",
        "mattpocock/skills/writing-for-agents",
    ],
};
