// Domain combo: Cloud Security & Posture — curates orphan-auditing/securing/configuring + cloud subset of orphan-implementing (always-suggested domain combo: requires: [] intentionally for visibility)
export const cloudSecurityCombo = {
  id: 'cloud-security',
  name: 'Cloud Security & Posture',
  requires: [] as string[],
  skills: [
    'Gabox301/SkillIndex/auditing-aws-s3-bucket-permissions',
    'Gabox301/SkillIndex/auditing-cloud-with-cis-benchmarks',
    'Gabox301/SkillIndex/auditing-gcp-iam-permissions',
    'Gabox301/SkillIndex/auditing-kubernetes-cluster-rbac',
    'Gabox301/SkillIndex/auditing-azure-active-directory-configuration',
    'Gabox301/SkillIndex/auditing-entra-id-with-aadinternals',
    'Gabox301/SkillIndex/securing-aws-iam-permissions',
    'Gabox301/SkillIndex/securing-azure-with-microsoft-defender',
    'Gabox301/SkillIndex/securing-kubernetes-on-cloud',
    'Gabox301/SkillIndex/securing-container-registry-images',
    'Gabox301/SkillIndex/configuring-aws-verified-access-for-ztna',
    'Gabox301/SkillIndex/configuring-identity-aware-proxy-with-google-iap',
    'Gabox301/SkillIndex/configuring-tls-1-3-for-secure-communications',
    'Gabox301/SkillIndex/configuring-zscaler-private-access-for-ztna',
    'Gabox301/SkillIndex/implementing-aws-config-rules-for-compliance',
    'Gabox301/SkillIndex/implementing-aws-iam-permission-boundaries',
    'Gabox301/SkillIndex/implementing-aws-macie-for-data-classification',
    'Gabox301/SkillIndex/implementing-aws-security-hub',
    'Gabox301/SkillIndex/implementing-aws-security-hub-compliance',
    'Gabox301/SkillIndex/implementing-azure-ad-privileged-identity-management',
    'Gabox301/SkillIndex/implementing-azure-defender-for-cloud',
    'Gabox301/SkillIndex/implementing-gcp-binary-authorization',
    'Gabox301/SkillIndex/implementing-gcp-organization-policy-constraints',
    'Gabox301/SkillIndex/implementing-gcp-vpc-firewall-rules',
    'Gabox301/SkillIndex/implementing-zero-trust-network-access',
  ],
};

