import type { ComboSkill } from '../types.ts';

// Cross-technology framework combos (previously inline in skills-map.ts).
export const FRAMEWORK_COMBOS: ComboSkill[] = [
  {
    id: "expo-tailwind",
    name: "Expo + Tailwind CSS",
    requires: ["expo", "tailwind"],
    skills: ["expo/skills/expo-tailwind-setup"],
  },
  {
    id: "react-hook-form-zod",
    name: "React Hook Form + Zod",
    requires: ["react-hook-form", "zod"],
    skills: ["pproenca/dot-skills/zod"],
  },
  {
    id: "nextjs-supabase",
    name: "Next.js + Supabase",
    requires: ["nextjs", "supabase"],
    skills: ["supabase/agent-skills/supabase-postgres-best-practices"],
  },
  {
    id: "react-native-expo",
    name: "React Native + Expo",
    requires: ["react-native", "expo"],
    skills: ["expo/skills/building-native-ui", "sleekdotdesign/agent-skills/design-mobile-apps"],
  },
  {
    id: "nextjs-vercel-ai",
    name: "Next.js + Vercel AI SDK",
    requires: ["nextjs", "vercel-ai"],
    skills: ["vercel/ai/use-ai-sdk", "vercel-labs/next-skills/next-best-practices"],
  },
  {
    id: "nextjs-playwright",
    name: "Next.js + Playwright",
    requires: ["nextjs", "playwright"],
    skills: ["currents-dev/playwright-best-practices-skill/playwright-best-practices"],
  },
  {
    id: "react-shadcn",
    name: "React + shadcn/ui",
    requires: ["react", "shadcn"],
    skills: ["shadcn/ui/shadcn", "vercel-labs/agent-skills/react-best-practices"],
  },
  {
    id: "tailwind-shadcn",
    name: "Tailwind CSS + shadcn/ui",
    requires: ["tailwind", "shadcn"],
    skills: ["secondsky/claude-skills/tailwind-v4-shadcn"],
  },
  {
    id: "gsap-react",
    name: "GSAP + React",
    requires: ["gsap", "react"],
    skills: ["greensock/gsap-skills/gsap-react"],
  },
  {
    id: "cloudflare-vite",
    name: "Cloudflare + Vite",
    requires: ["cloudflare", "vite"],
    skills: ["cloudflare/vinext/migrate-to-vinext"],
  },
  {
    id: "node-express",
    name: "Node.js + Express",
    requires: ["node", "express"],
    skills: ["aj-geddes/useful-ai-prompts/nodejs-express-server"],
  },
  {
    id: "nextjs-clerk",
    name: "Next.js + Clerk",
    requires: ["nextjs", "clerk"],
    skills: ["clerk/skills/clerk-nextjs-patterns"],
  },
  {
    id: "nuxt-clerk",
    name: "Nuxt + Clerk",
    requires: ["nuxt", "clerk"],
    skills: ["clerk/skills/clerk-nuxt-patterns"],
  },
  {
    id: "vue-clerk",
    name: "Vue + Clerk",
    requires: ["vue", "clerk"],
    skills: ["clerk/skills/clerk-vue-patterns"],
  },
  {
    id: "react-clerk",
    name: "React + Clerk",
    requires: ["react", "clerk"],
    skills: ["clerk/skills/clerk-react-patterns"],
  },
  {
    id: "astro-clerk",
    name: "Astro + Clerk",
    requires: ["astro", "clerk"],
    skills: ["clerk/skills/clerk-astro-patterns"],
  },
  {
    id: "expo-clerk",
    name: "Expo + Clerk",
    requires: ["expo", "clerk"],
    skills: ["clerk/skills/clerk-expo-patterns"],
  },
  {
    id: "react-react-three-fiber",
    name: "React + React Three Fiber",
    requires: ["threejs", "react", "@react-three/fiber"],
    skills: ["vercel-labs/json-render/react-three-fiber"],
  },
  {
    id: "react-router-clerk",
    name: "React Router + Clerk",
    requires: ["react-router", "clerk"],
    skills: ["clerk/skills/clerk-react-router-patterns", "clerk/skills/clerk-setup", "clerk/skills/clerk"],
  },
  {
    id: "tanstack-clerk",
    name: "TanStack Start + Clerk",
    requires: ["tanstack-start", "clerk"],
    skills: ["clerk/skills/clerk-tanstack-patterns", "clerk/skills/clerk-setup", "clerk/skills/clerk"],
  },
  {
    id: "chrome-extension-clerk",
    name: "Chrome Extension + Clerk",
    requires: ["chrome-extension", "clerk"],
    skills: ["clerk/skills/clerk-chrome-extension-patterns", "clerk/skills/clerk-setup", "clerk/skills/clerk"],
  },
  {
    id: "swiftui-clerk",
    name: "SwiftUI + Clerk",
    requires: ["swiftui", "clerk"],
    skills: ["clerk/skills/clerk-swift", "clerk/skills/clerk-setup", "clerk/skills/clerk"],
  },
  {
    id: "android-clerk",
    name: "Android + Clerk",
    requires: ["android", "clerk"],
    skills: ["clerk/skills/clerk-android", "clerk/skills/clerk-setup", "clerk/skills/clerk"],
  },
  {
    id: "rails-rspec",
    name: "Ruby on Rails + RSpec",
    requires: ["rails", "rspec"],
    skills: ["igmarin/rails-agent-skills/rails-tdd-slices", "igmarin/rails-agent-skills/rails-bug-triage"],
  },
  {
    id: "rails-sidekiq",
    name: "Ruby on Rails + Sidekiq",
    requires: ["rails", "sidekiq"],
    skills: [],
  },
];
