// Domain combo: Security Operations — curates orphan-detecting/analyzing (SOC/SIEM, always-suggested domain combo: requires: [] intentionally for visibility via detectCombos every([])=true)
export const securityOperationsCombo = {
  id: 'security-operations',
  name: 'Security Operations (SOC/SIEM)',
  requires: [] as string[],
  skills: [
    'Gabox301/SkillIndex/detecting-aws-cloudtrail-anomalies',
    'Gabox301/SkillIndex/detecting-aws-credential-exposure-with-trufflehog',
    'Gabox301/SkillIndex/detecting-aws-guardduty-findings-automation',
    'Gabox301/SkillIndex/detecting-aws-iam-privilege-escalation',
    'Gabox301/SkillIndex/detecting-azure-lateral-movement',
    'Gabox301/SkillIndex/detecting-azure-service-principal-abuse',
    'Gabox301/SkillIndex/detecting-lateral-movement-in-network',
    'Gabox301/SkillIndex/detecting-lateral-movement-with-splunk',
    'Gabox301/SkillIndex/detecting-lateral-movement-with-zeek',
    'Gabox301/SkillIndex/detecting-credential-dumping-techniques',
    'Gabox301/SkillIndex/detecting-command-and-control-over-dns',
    'Gabox301/SkillIndex/detecting-beaconing-patterns-with-zeek',
    'Gabox301/SkillIndex/detecting-dcsync-attack-in-active-directory',
    'Gabox301/SkillIndex/detecting-kerberoasting-attacks',
    'Gabox301/SkillIndex/analyzing-apt-group-with-mitre-navigator',
    'Gabox301/SkillIndex/analyzing-threat-actor-ttps-with-mitre-attack',
    'Gabox301/SkillIndex/analyzing-threat-actor-ttps-with-mitre-navigator',
    'Gabox301/SkillIndex/analyzing-security-logs-with-splunk',
    'Gabox301/SkillIndex/analyzing-windows-event-logs-in-splunk',
    'Gabox301/SkillIndex/analyzing-azure-activity-logs-for-threats',
    'Gabox301/SkillIndex/analyzing-kubernetes-audit-logs',
    'Gabox301/SkillIndex/analyzing-api-gateway-access-logs',
    'Gabox301/SkillIndex/analyzing-indicators-of-compromise',
    'Gabox301/SkillIndex/analyzing-network-traffic-for-incidents',
    'Gabox301/SkillIndex/analyzing-cyber-kill-chain',
  ],
};

