export const clerkTech = {
  id: 'clerk',
  name: 'Clerk',
  detect: {
    packages: [
      '@clerk/nextjs',
      '@clerk/remix',
      '@clerk/astro',
      '@clerk/express',
      '@clerk/fastify',
      '@clerk/nuxt',
      '@clerk/vue',
      '@clerk/react',
      '@clerk/expo',
      '@clerk/tanstack-react-start',
      '@clerk/react-router',
      '@clerk/chrome-extension',
      '@clerk/backend',
    ],
    packagePatterns: [/^@clerk\//],
    configFileContent: [
      { files: ['Package.swift'], patterns: ['clerk/clerk-ios', 'ClerkSDK'] },
      { scanGradleLayout: true, patterns: ['com.clerk'] },
    ],
  },
  skills: [
    'clerk/skills/clerk',
    'clerk/skills/clerk-setup',
    'clerk/skills/clerk-custom-ui',
    'clerk/skills/clerk-backend-api',
    'clerk/skills/clerk-orgs',
    'clerk/skills/clerk-webhooks',
    'clerk/skills/clerk-testing',
  ],
};
