pub const AGENT_FOLDER_MAP: &[(&str, &str)] = &[
    (".antigravity", "antigravity"),
    (".claude", "claude-code"),
    (".cline", "cline"),
    (".codebuddy", "codebuddy"),
    (".codex", "codex"),
    (".commandcode", "command-code"),
    (".continue", "continue"),
    (".crush", "crush"),
    (".cursor", "cursor"),
    (".factory", "droid"),
    (".gemini", "gemini-cli"),
    (".github", "github-copilot"),
    (".goose", "goose"),
    (".junie", "junie"),
    (".kilocode", "kilo-code"),
    (".kiro", "kiro-cli"),
    (".neovate", "neovate"),
    (".opencode", "opencode"),
    (".openhands", "openhands"),
    (".pi", "pi"),
    (".qoder", "qoder"),
    (".qwen", "qwen-code"),
    (".roo", "roo-code"),
    (".trae", "trae"),
    (".windsurf", "windsurf"),
    (".zencoder", "zencoder"),
];
