export const agentWorkflows = {
  id: "agent-workflows",
  name: "Agent Development Workflows",
  detect: {  },
  skills: [
    "Gabox301/SkillIndex/branch-pr",
    "Gabox301/SkillIndex/chained-pr",
    "Gabox301/SkillIndex/cognitive-doc-design",
    "Gabox301/SkillIndex/comment-writer",
    "Gabox301/SkillIndex/copywriting",
    "Gabox301/SkillIndex/find-skills",
    "Gabox301/SkillIndex/gentle-ai-bench",
    "Gabox301/SkillIndex/go-testing",
    "Gabox301/SkillIndex/graphify",
    "Gabox301/SkillIndex/issue-creation",
    "Gabox301/SkillIndex/judgment-day",
    "Gabox301/SkillIndex/rdd-defect-workflow",
    "Gabox301/SkillIndex/skill-creator",
    "Gabox301/SkillIndex/skill-improver",
    "Gabox301/SkillIndex/skill-registry",
    "Gabox301/SkillIndex/supabase",
    "Gabox301/SkillIndex/systemic-issue-triage",
    "Gabox301/SkillIndex/vercel-react-best-practices",
    "Gabox301/SkillIndex/web-design-guidelines",
    "Gabox301/SkillIndex/work-unit-commits",
  ],
};
