export const penetrationTestingTech = {
  id: "penetration-testing",
  name: "Penetration Testing",
  detect: { "configFileContent": { "files": ["pentest-report.md", "engagement-plan.md", "engagement-scope.json"], "patterns": ["penetration test", "red team", "engagement"] } },
  skills: [
    "Gabox301/SkillIndex/conducting-api-security-testing",
    "Gabox301/SkillIndex/conducting-cloud-incident-response",
    "Gabox301/SkillIndex/conducting-cloud-penetration-testing",
    "Gabox301/SkillIndex/conducting-cyber-risk-assessment-with-nist-800-30",
    "Gabox301/SkillIndex/conducting-domain-persistence-with-dcsync",
    "Gabox301/SkillIndex/conducting-external-reconnaissance-with-osint",
    "Gabox301/SkillIndex/conducting-full-scope-red-team-engagement",
    "Gabox301/SkillIndex/conducting-internal-network-penetration-test",
    "Gabox301/SkillIndex/conducting-internal-reconnaissance-with-bloodhound-ce",
    "Gabox301/SkillIndex/conducting-malware-incident-response",
    "Gabox301/SkillIndex/conducting-man-in-the-middle-attack-simulation",
    "Gabox301/SkillIndex/conducting-memory-forensics-with-volatility",
    "Gabox301/SkillIndex/conducting-mobile-app-penetration-test",
    "Gabox301/SkillIndex/conducting-network-penetration-test",
    "Gabox301/SkillIndex/conducting-pass-the-ticket-attack",
    "Gabox301/SkillIndex/conducting-phishing-incident-response",
    "Gabox301/SkillIndex/conducting-post-incident-lessons-learned",
    "Gabox301/SkillIndex/conducting-social-engineering-penetration-test",
    "Gabox301/SkillIndex/conducting-social-engineering-pretext-call",
    "Gabox301/SkillIndex/conducting-spearphishing-simulation-campaign",
    "Gabox301/SkillIndex/conducting-wireless-network-penetration-test",
  ],
};
