export const securityAnalysisTech = {
  id: 'security-analysis',
  name: 'Security Analysis',
  detect: {
    configFileContent: {
      files: ['SECURITY.md', 'analysis.json'],
      patterns: ['analysis', 'forensics', 'malware'],
    },
  },
  skills: [
    'Gabox301/SkillIndex/analyzing-active-directory-acl-abuse',
    'Gabox301/SkillIndex/analyzing-android-malware-with-apktool',
    'Gabox301/SkillIndex/analyzing-api-gateway-access-logs',
    'Gabox301/SkillIndex/analyzing-apt-group-with-mitre-navigator',
    'Gabox301/SkillIndex/analyzing-azure-activity-logs-for-threats',
    'Gabox301/SkillIndex/analyzing-bootkit-and-rootkit-samples',
    'Gabox301/SkillIndex/analyzing-browser-forensics-with-hindsight',
    'Gabox301/SkillIndex/analyzing-campaign-attribution-evidence',
    'Gabox301/SkillIndex/analyzing-certificate-transparency-for-phishing',
    'Gabox301/SkillIndex/analyzing-cloud-storage-access-patterns',
    'Gabox301/SkillIndex/analyzing-cobalt-strike-beacon-configuration',
    'Gabox301/SkillIndex/analyzing-cobaltstrike-malleable-c2-profiles',
    'Gabox301/SkillIndex/analyzing-command-and-control-communication',
    'Gabox301/SkillIndex/analyzing-cyber-kill-chain',
    'Gabox301/SkillIndex/analyzing-disk-image-with-autopsy',
    'Gabox301/SkillIndex/analyzing-dns-logs-for-exfiltration',
    'Gabox301/SkillIndex/analyzing-docker-container-forensics',
    'Gabox301/SkillIndex/analyzing-email-headers-for-phishing-investigation',
    'Gabox301/SkillIndex/analyzing-ethereum-smart-contract-vulnerabilities',
    'Gabox301/SkillIndex/analyzing-golang-malware-with-ghidra',
    'Gabox301/SkillIndex/analyzing-heap-spray-exploitation',
    'Gabox301/SkillIndex/analyzing-indicators-of-compromise',
    'Gabox301/SkillIndex/analyzing-ios-app-security-with-objection',
    'Gabox301/SkillIndex/analyzing-kubernetes-audit-logs',
    'Gabox301/SkillIndex/analyzing-linux-audit-logs-for-intrusion',
    'Gabox301/SkillIndex/analyzing-linux-elf-malware',
    'Gabox301/SkillIndex/analyzing-linux-kernel-rootkits',
    'Gabox301/SkillIndex/analyzing-linux-system-artifacts',
    'Gabox301/SkillIndex/analyzing-lnk-file-and-jump-list-artifacts',
    'Gabox301/SkillIndex/analyzing-macro-malware-in-office-documents',
    'Gabox301/SkillIndex/analyzing-malicious-pdf-with-peepdf',
    'Gabox301/SkillIndex/analyzing-malicious-url-with-urlscan',
    'Gabox301/SkillIndex/analyzing-malware-behavior-with-cuckoo-sandbox',
    'Gabox301/SkillIndex/analyzing-malware-family-relationships-with-malpedia',
    'Gabox301/SkillIndex/analyzing-malware-persistence-with-autoruns',
    'Gabox301/SkillIndex/analyzing-malware-sandbox-evasion-techniques',
    'Gabox301/SkillIndex/analyzing-memory-dumps-with-volatility',
    'Gabox301/SkillIndex/analyzing-memory-forensics-with-lime-and-volatility',
    'Gabox301/SkillIndex/analyzing-mft-for-deleted-file-recovery',
    'Gabox301/SkillIndex/analyzing-network-covert-channels-in-malware',
    'Gabox301/SkillIndex/analyzing-network-flow-data-with-netflow',
    'Gabox301/SkillIndex/analyzing-network-packets-with-scapy',
    'Gabox301/SkillIndex/analyzing-network-traffic-for-incidents',
    'Gabox301/SkillIndex/analyzing-network-traffic-of-malware',
    'Gabox301/SkillIndex/analyzing-network-traffic-with-wireshark',
    'Gabox301/SkillIndex/analyzing-office365-audit-logs-for-compromise',
    'Gabox301/SkillIndex/analyzing-outlook-pst-for-email-forensics',
    'Gabox301/SkillIndex/analyzing-packed-malware-with-upx-unpacker',
    'Gabox301/SkillIndex/analyzing-pdf-malware-with-pdfid',
    'Gabox301/SkillIndex/analyzing-persistence-mechanisms-in-linux',
    'Gabox301/SkillIndex/analyzing-powershell-empire-artifacts',
    'Gabox301/SkillIndex/analyzing-powershell-script-block-logging',
    'Gabox301/SkillIndex/analyzing-prefetch-files-for-execution-history',
    'Gabox301/SkillIndex/analyzing-ransomware-encryption-mechanisms',
    'Gabox301/SkillIndex/analyzing-ransomware-leak-site-intelligence',
    'Gabox301/SkillIndex/analyzing-ransomware-network-indicators',
    'Gabox301/SkillIndex/analyzing-ransomware-payment-wallets',
    'Gabox301/SkillIndex/analyzing-sbom-for-supply-chain-vulnerabilities',
    'Gabox301/SkillIndex/analyzing-security-logs-with-splunk',
    'Gabox301/SkillIndex/analyzing-slack-space-and-file-system-artifacts',
    'Gabox301/SkillIndex/analyzing-supply-chain-malware-artifacts',
    'Gabox301/SkillIndex/analyzing-threat-actor-ttps-with-mitre-attack',
    'Gabox301/SkillIndex/analyzing-threat-actor-ttps-with-mitre-navigator',
    'Gabox301/SkillIndex/analyzing-threat-intelligence-feeds',
    'Gabox301/SkillIndex/analyzing-threat-landscape-with-misp',
    'Gabox301/SkillIndex/analyzing-tls-certificate-transparency-logs',
    'Gabox301/SkillIndex/analyzing-typosquatting-domains-with-dnstwist',
    'Gabox301/SkillIndex/analyzing-uefi-bootkit-persistence',
    'Gabox301/SkillIndex/analyzing-usb-device-connection-history',
    'Gabox301/SkillIndex/analyzing-web-server-logs-for-intrusion',
    'Gabox301/SkillIndex/analyzing-windows-amcache-artifacts',
    'Gabox301/SkillIndex/analyzing-windows-event-logs-in-splunk',
    'Gabox301/SkillIndex/analyzing-windows-lnk-files-for-artifacts',
    'Gabox301/SkillIndex/analyzing-windows-prefetch-with-python',
    'Gabox301/SkillIndex/analyzing-windows-registry-for-artifacts',
    'Gabox301/SkillIndex/analyzing-windows-shellbag-artifacts',
  ],
};
