export const securityToolingTech = {
  id: 'security-tooling',
  name: 'Security Tooling & Operations',
  detect: {
    configFileContent: {
      files: ['security-tooling.md', 'security-ops.md'],
      patterns: ['security operations', 'threat intelligence', 'siem'],
    },
  },
  skills: [
    'Gabox301/SkillIndex/abusing-dpapi-for-credential-access',
    'Gabox301/SkillIndex/abusing-shadow-credentials-for-privesc',
    'Gabox301/SkillIndex/achieving-cmmc-level-2-compliance',
    'Gabox301/SkillIndex/acquiring-disk-image-with-dd-and-dcfldd',
    'Gabox301/SkillIndex/assessing-vector-and-embedding-weaknesses',
    'Gabox301/SkillIndex/attacking-entra-id-with-roadtools',
    'Gabox301/SkillIndex/attacking-oauth-with-device-code-phishing',
    'Gabox301/SkillIndex/automating-ioc-enrichment',
    'Gabox301/SkillIndex/benchmarking-kubernetes-with-kube-bench',
    'Gabox301/SkillIndex/bypassing-authentication-with-forced-browsing',
    'Gabox301/SkillIndex/coercing-authentication-with-coercer-petitpotam',
    'Gabox301/SkillIndex/collecting-indicators-of-compromise',
    'Gabox301/SkillIndex/collecting-open-source-intelligence',
    'Gabox301/SkillIndex/collecting-threat-intelligence-with-misp',
    'Gabox301/SkillIndex/collecting-volatile-evidence-from-compromised-host',
    'Gabox301/SkillIndex/containing-active-breach',
    'Gabox301/SkillIndex/continuous-llm-red-teaming-with-promptfoo',
    'Gabox301/SkillIndex/correlating-security-events-in-qradar',
    'Gabox301/SkillIndex/correlating-threat-campaigns',
    'Gabox301/SkillIndex/defending-llms-with-guardrails',
    'Gabox301/SkillIndex/deobfuscating-javascript-malware',
    'Gabox301/SkillIndex/deobfuscating-powershell-obfuscated-malware',
    'Gabox301/SkillIndex/designing-adversary-engagement-with-mitre-engage',
    'Gabox301/SkillIndex/emulating-cloud-attacks-with-stratus-red-team',
    'Gabox301/SkillIndex/enumerating-cloud-with-cloudfox',
    'Gabox301/SkillIndex/eradicating-malware-from-infected-systems',
    'Gabox301/SkillIndex/escaping-containers-to-host',
    'Gabox301/SkillIndex/evaluating-threat-intelligence-platforms',
    'Gabox301/SkillIndex/fleet-hunting-with-velociraptor',
    'Gabox301/SkillIndex/generating-and-analyzing-sboms',
    'Gabox301/SkillIndex/generating-forensic-timelines-with-hayabusa',
    'Gabox301/SkillIndex/generating-threat-intelligence-reports',
    'Gabox301/SkillIndex/hardening-docker-containers-for-production',
    'Gabox301/SkillIndex/hardening-docker-daemon-configuration',
    'Gabox301/SkillIndex/hardening-linux-endpoint-with-cis-benchmark',
    'Gabox301/SkillIndex/hardening-windows-endpoint-with-cis-benchmark',
    'Gabox301/SkillIndex/integrating-dast-with-owasp-zap-in-pipeline',
    'Gabox301/SkillIndex/integrating-sast-into-github-actions-pipeline',
    'Gabox301/SkillIndex/intercepting-mobile-traffic-with-burpsuite',
    'Gabox301/SkillIndex/investigating-insider-threat-indicators',
    'Gabox301/SkillIndex/investigating-phishing-email-incident',
    'Gabox301/SkillIndex/investigating-ransomware-attack-artifacts',
    'Gabox301/SkillIndex/managing-cloud-identity-with-okta',
    'Gabox301/SkillIndex/managing-intelligence-lifecycle',
    'Gabox301/SkillIndex/managing-third-party-vendor-risk',
    'Gabox301/SkillIndex/mapping-attack-paths-with-bloodhound-ce',
    'Gabox301/SkillIndex/mapping-mitre-attack-techniques',
    'Gabox301/SkillIndex/migrating-to-post-quantum-cryptography',
    'Gabox301/SkillIndex/modeling-threats-with-opencti',
    'Gabox301/SkillIndex/monitoring-darkweb-sources',
    'Gabox301/SkillIndex/monitoring-scada-modbus-traffic-anomalies',
    'Gabox301/SkillIndex/moving-laterally-with-netexec',
    'Gabox301/SkillIndex/operating-havoc-c2',
    'Gabox301/SkillIndex/operating-sliver-c2',
    'Gabox301/SkillIndex/operationalizing-misp-threat-feeds',
    'Gabox301/SkillIndex/orchestrating-llm-attacks-with-pyrit',
    'Gabox301/SkillIndex/parsing-artifacts-with-eric-zimmerman-tools',
    'Gabox301/SkillIndex/post-exploiting-microsoft-graph-with-graphrunner',
    'Gabox301/SkillIndex/prioritizing-vulnerabilities-with-cvss-scoring',
    'Gabox301/SkillIndex/processing-stix-taxii-feeds',
    'Gabox301/SkillIndex/profiling-threat-actor-groups',
    'Gabox301/SkillIndex/recovering-deleted-files-with-photorec',
    'Gabox301/SkillIndex/recovering-from-ransomware-attack',
    'Gabox301/SkillIndex/red-teaming-llms-with-garak',
    'Gabox301/SkillIndex/relaying-ntlm-for-adcs-esc8',
    'Gabox301/SkillIndex/remediating-s3-bucket-misconfiguration',
    'Gabox301/SkillIndex/tracking-threat-actor-infrastructure',
    'Gabox301/SkillIndex/validating-backup-integrity-for-recovery',
    'Gabox301/SkillIndex/validating-tpm-measured-boot-attestation',
    'Gabox301/SkillIndex/verifying-build-provenance-with-slsa-sigstore',
  ],
};
