export const securityEngineeringTech = {
  id: 'security-engineering',
  name: 'Security Engineering',
  detect: {
    configFileContent: {
      files: ['detection-engineering.md', 'soc-runbook.md'],
      patterns: ['detection engineering', 'sigma rule', 'soc playbook'],
    },
  },
  skills: [
    'Gabox301/SkillIndex/building-adversary-infrastructure-tracking-system',
    'Gabox301/SkillIndex/building-attack-pattern-library-from-cti-reports',
    'Gabox301/SkillIndex/building-automated-malware-submission-pipeline',
    'Gabox301/SkillIndex/building-c2-infrastructure-with-sliver-framework',
    'Gabox301/SkillIndex/building-c2-redirector-infrastructure',
    'Gabox301/SkillIndex/building-cloud-siem-with-sentinel',
    'Gabox301/SkillIndex/building-detection-rule-with-splunk-spl',
    'Gabox301/SkillIndex/building-detection-rules-with-sigma',
    'Gabox301/SkillIndex/building-devsecops-pipeline-with-gitlab-ci',
    'Gabox301/SkillIndex/building-identity-federation-with-saml-azure-ad',
    'Gabox301/SkillIndex/building-identity-governance-lifecycle-process',
    'Gabox301/SkillIndex/building-incident-response-dashboard',
    'Gabox301/SkillIndex/building-incident-response-playbook',
    'Gabox301/SkillIndex/building-incident-timeline-with-timesketch',
    'Gabox301/SkillIndex/building-ioc-defanging-and-sharing-pipeline',
    'Gabox301/SkillIndex/building-ioc-enrichment-pipeline-with-opencti',
    'Gabox301/SkillIndex/building-malware-incident-communication-template',
    'Gabox301/SkillIndex/building-patch-tuesday-response-process',
    'Gabox301/SkillIndex/building-phishing-reporting-button-workflow',
    'Gabox301/SkillIndex/building-ransomware-playbook-with-cisa-framework',
    'Gabox301/SkillIndex/building-red-team-c2-infrastructure-with-havoc',
    'Gabox301/SkillIndex/building-role-mining-for-rbac-optimization',
    'Gabox301/SkillIndex/building-soc-escalation-matrix',
    'Gabox301/SkillIndex/building-soc-metrics-and-kpi-tracking',
    'Gabox301/SkillIndex/building-soc-playbook-for-ransomware',
    'Gabox301/SkillIndex/building-super-timelines-with-plaso',
    'Gabox301/SkillIndex/building-threat-actor-profile-from-osint',
    'Gabox301/SkillIndex/building-threat-feed-aggregation-with-misp',
    'Gabox301/SkillIndex/building-threat-hunt-hypothesis-framework',
    'Gabox301/SkillIndex/building-threat-intelligence-enrichment-in-splunk',
    'Gabox301/SkillIndex/building-threat-intelligence-feed-integration',
    'Gabox301/SkillIndex/building-threat-intelligence-platform',
    'Gabox301/SkillIndex/building-vulnerability-aging-and-sla-tracking',
    'Gabox301/SkillIndex/building-vulnerability-dashboard-with-defectdojo',
    'Gabox301/SkillIndex/building-vulnerability-exception-tracking-system',
    'Gabox301/SkillIndex/building-vulnerability-scanning-workflow',
  ],
};
