export const securityTestingTech = {
  id: "security-testing",
  name: "Security Testing",
  detect: { "configFileContent": { "files": ["security-testing.md", "owasp-test-plan.md"], "patterns": ["owasp", "security testing", "attack surface"] } },
  skills: [
    "Gabox301/SkillIndex/testing-android-intents-for-vulnerabilities",
    "Gabox301/SkillIndex/testing-api-authentication-weaknesses",
    "Gabox301/SkillIndex/testing-api-for-broken-object-level-authorization",
    "Gabox301/SkillIndex/testing-api-for-mass-assignment-vulnerability",
    "Gabox301/SkillIndex/testing-api-security-with-owasp-top-10",
    "Gabox301/SkillIndex/testing-cors-misconfiguration",
    "Gabox301/SkillIndex/testing-for-broken-access-control",
    "Gabox301/SkillIndex/testing-for-business-logic-vulnerabilities",
    "Gabox301/SkillIndex/testing-for-email-header-injection",
    "Gabox301/SkillIndex/testing-for-host-header-injection",
    "Gabox301/SkillIndex/testing-for-json-web-token-vulnerabilities",
    "Gabox301/SkillIndex/testing-for-open-redirect-vulnerabilities",
    "Gabox301/SkillIndex/testing-for-sensitive-data-exposure",
    "Gabox301/SkillIndex/testing-for-system-prompt-leakage",
    "Gabox301/SkillIndex/testing-for-xml-injection-vulnerabilities",
    "Gabox301/SkillIndex/testing-for-xss-vulnerabilities",
    "Gabox301/SkillIndex/testing-for-xss-vulnerabilities-with-burpsuite",
    "Gabox301/SkillIndex/testing-for-xxe-injection-vulnerabilities",
    "Gabox301/SkillIndex/testing-jwt-token-security",
    "Gabox301/SkillIndex/testing-mobile-api-authentication",
    "Gabox301/SkillIndex/testing-oauth2-implementation-flaws",
    "Gabox301/SkillIndex/testing-prompt-injection-in-rag-pipelines",
    "Gabox301/SkillIndex/testing-ransomware-recovery-procedures",
    "Gabox301/SkillIndex/testing-websocket-api-security",
  ],
};
